README.md

The Github pages link was pointing to the docs folder instead of the root. This change aligns Github settings with README.md

chore: fix Github pages link

---

docs/DatabaseCatalogAPI.yaml

- Added legacy_id
- Changed syntax of /feeds/gtfs/{id}/datasets to /feeds/{id}/datasets/gtfs (moved gtfs at the end)
- Added a /datasets endpoint to get a list of basic dataset data regardless of type.
- Reduced the number of common fields returned when obtaining a generic list of feeds of datasets.
- Added /datasets/{id} endpoint as per PR comment.

Minor changes to the API

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/documentation_improvement.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/PULL_REQUEST_TEMPLATE.md
.github/config.yml

Added issue and PR templates.
Mostly copied from gtfs-validator, with some adjustments.
Closes https://github.com/MobilityData/mobility-feed-api/issues/27

Create PR and issue templates

---

.github/workflows/api-deployer.yml
.github/workflows/api-dev.yml
README.md
infra/main.tf

**Summary:**
Add DB models generation to the API deployment job 
GCP cloud run API contains the DB models.

chore: update api deployment with db models 

---

api/src/database/database.py
api/src/feeds/impl/feeds_api_impl.py

**Summary:**
Currently the API runs a database query for every external foreign key it needs to fetch. This causes the `/v1/feeds` endpoint to return 1903 feed objects in 12.99 seconds (according to PostMan)
With these changes the endpoint returns under 600 milliseconds for the same amount of feed objects.

fix: Optimize feeds query

---

.github/workflows/build-test.yml
api/src/feeds/impl/feeds_api_impl.py
api/tests/test_datasets_api.py
api/tests/test_feeds_api.py
api/tests/test_metadata_api.py
docs/DatabaseCatalogAPI.yaml

**Summary:**
Issue: https://github.com/MobilityData/mobility-feed-api/issues/84
All endpoints are accessible now.
Also all unit tests pass now. I removed a test for an endpoint that no longer exists.
I did not enable unit tests in CI because they depend on existing data in docker database. We can enable it when we have implemented complete unit tests (@goorui is working on it)

fix: Renaming API endpoints to resolve conflicting subpaths

---

.github/workflows/db-update.yml

GitHub has deprecated set-output and will eventually make it unusable, so this is a preventative fix. See more info here: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Fix for deprecated of `set-output` in GH actions

---

api/.openapi-generator/FILES
docs/DatabaseCatalogAPI.yaml
liquibase/changelog.xml
liquibase/changes/feat_77.sql

**Summary:**
https://github.com/MobilityData/mobility-feed-api/issues/83
Removed FeedLog table through liquibase

refactor: remove feed log table and endpoint

---

api/src/feeds/impl/feeds_api_impl.py

**Summary:**
This PR removes the FeedLog model's reference from the API endpoint implementation file. This fixes the QA deployment, an example of a failing build [here](https://github.com/MobilityData/mobility-feed-api/actions/runs/6264420571/job/17011185401). 
Completes  #83 
FeedLog is removed and Qa deployment is successful. 

fix: remove FeedLog getter endpoint from implementation function

---

api/src/feeds/impl/feeds_api_impl.py
api/tests/test_database.py
api/tests/test_feeds_api.py
docs/DatabaseCatalogAPI.yaml

**Summary:**
Closes #82 
Enable sorting on gtfs_feeds api

feat: GTFS feeds sorting by external_id and country_code

---

api/tests/test_database.py

**Summary:**
`test_merge_gtfs_feed` fails because `get_gtfs_feeds` requires a new param.  This was missed in the original PR.
`test_merge_gtfs_feed` should call `get_gtfs_feeds` successfully. 

Fix failing test `test_merge_gtfs_feed` 

---

web-app/src/app/screens/Account.tsx
web-app/src/app/services/profile-service.ts
web-app/src/app/store/saga/auth-saga.ts
web-app/src/app/types.ts

**Summary:**
display both refresh and access tokens in UI 
Closes #100 

feat: 100 display token in api UI

---

web-app/src/app/screens/Account.tsx
web-app/src/app/store/profile-reducer.ts
web-app/src/app/store/saga/profile-saga.ts

**Summary:**
Closes #136 
1. turn off Wifi
2. Click Refresh Access Token button
3. A snack bar with error message shown on the top center of your browser
New Testing steps:
Login
Click generate access token
Turn off Wifi
Click refresh access token icon button
A snackbar showing error message should displayed

feat: show a snackbar when refresh access token API call failed

---

infra/functions-python/main.tf

**Summary:**
GCP cloud storage buckets have to be unique. This PR guarantees that the python functions bucket has a unique name.
The bucket name contains a `mobility-feeds` prefix plus an environment suffix, making it unique per environment.

fix: duplicate name on python functions buckete

---

web-app/src/app/router/ProtectedRoute.tsx
web-app/src/app/services/profile-service.ts
web-app/src/app/store/profile-reducer.ts
web-app/src/app/store/selectors.ts

**Summary:**
Closes #155
1. Login
2. Open developer console, choose slow 3G as network setting
3. Click Refresh button of browser
4. You'll see a spinner 
5. Click Generate Access Token
6. You'll see the token generated

fix: 155 currentuser is always null on the first call of appauth

---

web-app/cypress/e2e/resetpassword.cy.ts
web-app/src/app/router/Router.tsx
web-app/src/app/screens/ForgotPassword.tsx
web-app/src/app/store/profile-reducer.ts
web-app/src/app/store/profile-selectors.ts
web-app/src/app/store/saga/auth-saga.ts
web-app/src/app/types.ts

**Summary:**
Reset (forgot) password auth workflow
Closes #141 
Related to #188 
- Log out if logged in
- From the Login screen click on `Forgot your password? Reset Here.`. You should then be redirected to the password resetting screen
- Type your registered email and submit
- Reset your email by following the instructions on the email you received
- Log in with your new password

feat: Reset (forgot) password auth workflow

---

api/src/feeds/impl/feeds_api_impl.py
api/src/scripts/populate_db.py
docs/DatabaseCatalogAPI.yaml
docs/DatabaseCatalogAPI_IAP.yaml

**Summary:**
closes #194 
Added feat_contact_email in openAPI config and in the populate-db python script.
This PR goes with this mobility_database_catalog PR: https://github.com/MobilityData/mobility-database-catalogs/pull/316
`feed_contact_email` added to all the feeds endpoints response
`feed_contact_email` added to the swagger
- Generate the DB locally (see steps in https://github.com/MobilityData/mobility-feed-api/blob/main/README.md)
- Check that there is a `feed_contact_email` column added to the `feeds` table. You can use psql or pgAdmin4 for that)
- Use the sources.csv file generated by the mobility-database-catalog github action. 
- Fill the DB with populate-db.py script.
- Call the feeds endpoints from the API.
- Check that there is a …

feat: Add feed_contact_email

---

docs/DatabaseCatalogAPI.yaml
docs/DatabaseCatalogAPI_IAP.yaml

**Summary:**
Fixes the 500 response from the API when limit parameter passed is negative. https://github.com/MobilityData/mobility-feed-api/issues/190
Returns 422 with the below JSON body like offset parameter.

fix: 500 when limit is -1

---

infra/functions-python/main.tf

**Summary:**
PR #196  changed the service account to be used in the Python functions and broke the deployment. 
The correct service account is referenced by the python functions.

fix: python functions service account reference

---

web-app/cypress/e2e/resetpassword.cy.ts
web-app/cypress/e2e/signup.cy.ts
web-app/src/app/screens/ChangePassword.tsx
web-app/src/app/screens/CompleteRegistration.tsx
web-app/src/app/screens/ForgotPassword.tsx
web-app/src/app/screens/SignIn.tsx
web-app/src/app/screens/SignUp.tsx

**Summary:**
Closes #206 
- validation error display fix on `SignIn`, `SignUp`, `CompleteRegistration`, `ResetPassword`, `ForgotPassword`
- changed error messages to be consistent
- updated e2e tests to reflect the changes
The validation error displays once the user submits the forms. Once the user has submitted the form once, the error will update upon any change to guide the user and let them know when the input's validation error was fixed.
Try the input boxes on any (or all) of the following pages:
- Sign In
- Sign Up
- Complete Registration (create a new account to see this page when you login for the first time)
- Reset Password
- Forgot Password (login to your account using the email and password method and click on `Change Password` from …

fix: input validation error display issue

---

.github/workflows/build-test.yml
functions-python/batch_datasets/src/main.py
functions-python/batch_datasets/tests/test_batch_datasets_main.py

**Summary:**
The GCP pub-sub global variable was loaded before mocks were applied. This enforced GCP credentials set and blocks external contributors from running tests on the local environment and forks. This PR remove the GCP credentials dependency by making the pub-sub client scoped to the main python function.
GCP credentials dependency is removed from local environment and GH forks.

chore: remove GCP credentials from build-test GH action

---

api/.openapi-generator/FILES
docs/DatabaseCatalogAPI.yaml

**Summary:**
Added validation_report model to GtfsDataset component. This PR only changes the OpenAPI schema; it doesn't implement the proposed design.
Closes #223 
Use you preferable swagger UI to verify the schema changes

OpenAPI schema changes to support validation report

---

web-app/src/app/constants/Navigation.ts
web-app/src/app/router/ProtectedRoute.tsx
web-app/src/app/router/Router.tsx
web-app/src/app/screens/PostRegistration.tsx
web-app/src/app/screens/SignIn.tsx
web-app/src/app/screens/SignUp.tsx
web-app/src/app/services/profile-service.ts
web-app/src/app/store/profile-reducer.ts
web-app/src/app/store/profile-selectors.ts
web-app/src/app/store/saga/auth-saga.ts
web-app/src/app/types.ts

**Summary:**
Adding the email verification to the UI.
Closes #177 
For users that sign up using the email and password method, they are locked out of using their account until email verification is complete. Users are redirected to the `verify-account` page where they can resend the email.
- Create a new account using email and password --> You should be redirected to `/verify-account` if the creation is successful 
- Click on `Resend Email` to validate that you receive a new email --> You should see a success message (see image bellow)
- Validate your account from your email --> Within a second you should be automatically redirected to the account page

feat: add email verification workflow in the UI 

---

web-app/package.json
web-app/src/app/components/Header.tsx
web-app/src/app/constants/Navigation.ts
web-app/yarn.lock

**Summary:**
Closes #205 
The hamburger navigation matches the desktop navigation
When the user is not authenticated:
When the user is authenticated:
- Reduce page width to <900px
- Click on hamburger navigation 
- Validate that the login button works properly
- Login to your account
- Click on the hamburger navigation once more
- Validate that the account options are available and match the desktop version (which you can see by increasing the page width to >=900px) 

fix: mobile navigation matches desktop navigation

---

integration-tests/src/endpoints/feeds.py
integration-tests/src/endpoints/gtfs_feeds.py
integration-tests/src/endpoints/integration_tests.py

**Summary:**
Part of #114 
✅ Added a 10 seconds timeout on `GET` requests
✅ Removed tests using the `sort` parameter
✅ Introduced tests using the `order_by` parameter
All integration tests now pass
Follow testing tips from #259 

fix: sorting/ordering integration tests update

---

.github/workflows/build-test.yml
scripts/db-gen.sh

`Build & Test` workflow started to fail with no code changes related to the workflow, [failing example](https://github.com/MobilityData/mobility-feed-api/actions/runs/7849817029/job/21423960180?pr=275).  I found multiple causes. The main issue is related to failures of the Liquibase container service at the starting time. This failure has been registered sporadically in local machines but, starting from today, is constantly reproduced at GitHub actions. The second issue found was a race condition between Liquibase and the testing database's healthy state.
- Replace the Liquibase service container with a locally installed package at Github actions.
- Reorder steps to allow enough time between docker-compose and Liquibase execution
Explain and/or show screenshots for how you expect the pull …

fix: unit tests failing due to local connection issues

---

.github/workflows/api-deployer.yml
.github/workflows/build-test.yml
.github/workflows/datasets-batch-deployer.yml

**Summary:**
This PR follows #275, replacing the liquibase docker container used in the rest of the workflows.
The following workflows work on GitHub:
- Deploy API - {Environment}, [successful execution](https://github.com/MobilityData/mobility-feed-api/actions/runs/7879448919)
- Deploy Historical Batch Processing - {Environment}, [successful execution](https://github.com/MobilityData/mobility-feed-api/actions/runs/7879472405)
Closes #281
Verify the the mentioned GitHub workflows are running successfully.

fix: liquibase docker failing on db gen steps

---

api/src/database/database.py
integration-tests/README.md
integration-tests/src/endpoints/gtfs_feeds.py
scripts/integration-tests.sh

**Summary:**
Closes #283 
✅ Introduces session rollback to avoid leaving transactions open when an error is thrown
✅ Added an integration test
When the server runs into an error related to a database call, the subsequent request remain unaffected by the previous error.
- Redeploy API QA
- Follow steps in `integration-tests/README.md` and run tests in QA using the filter `-c "GTFSFeedsEndpointTests"`-- test `GTFSFeedsEndpointTests.test_invalid_bb_input_followed_by_valid_request` should fail
- Follow steps in `integration-tests/README.md` and run tests in DEV using the filter `-c "GTFSFeedsEndpointTests"`-- test `GTFSFeedsEndpointTests.test_invalid_bb_input_followed_by_valid_request` should pass
Please make sure these boxes are checked before …

fix: transaction open generates 500 server error

---

api/.coveragerc
api/requirements.txt
api/src/feeds/impl/datasets_api_impl.py
api/tests/test_database.py
api/tests/test_feeds_api.py

**Summary:**
Closes #282 
✅  Added validation for bounding box filters (`dataset_latitudes` and `dataset_longitudes`) --> should be 2 comma separated floats
✅ Fix coverage on integration tests 
API returns a `400` status code when the values of the filters does not match proper formatting. 
API returns an empty array if the coordinates are invalid or do not match any stored dataset.
- Checkout branch
- Run api locally
- Use Swagger UI connected to `localhost` to test `/v1/gtfs_feed`
- Test different types of inputs for `dataset_latitudes` and `dataset_longitudes`
- Validate the behavior. 

fix: bounding box input validation

---

README.md
api/src/feeds/impl/datasets_api_impl.py
api/src/feeds/impl/error_handling.py
api/src/feeds/impl/feeds_api_impl.py
api/src/main.py
api/src/utils/date_utils.py
api/tests/conftest.py
api/tests/test_feeds_api.py
api/tests/test_utils/database.py
api/tests/utils/test_date_utils.py
docs/DatabaseCatalogAPI.yaml

**Summary:**
Changes:
- ~In testing steps, make sure that we can do partial matches (e.g just the date with no timestamp)~
Fixes #285 
- Start application locally 
- Open Postman hit the following endpoints:
-  http://localhost:8080/v1/gtfs_feeds/mdb-1/datasets?downloaded_before=2024-12-01T00:00:00Z
Expect HTTP 200 with body
```
[
{
.. all your 2024 datasets for mdb1 feed
}
]
```
-  http://localhost:8080/v1/gtfs_feeds/mdb-1/datasets?downloaded_before=2024
Expect HTTP 422 with body
```
{
"detail": "Invalid date format for 'downloaded_before'. Expected ISO 8601 format, example: '2021-01-01T00:00:00Z'"
}
```
-  http://localhost:8080/v1/gtfs_feeds/{id}/datasets?downloaded_after=2024
Expect HTTP 422 with body
```
{
"detail": "Invalid date format for …
```

fix: downloaded_at filter

---

web-app/src/app/components/Footer.tsx
web-app/src/app/router/Router.tsx
web-app/src/app/screens/PrivacyPolicy.tsx

**Summary:**
Closes #306 
This screen reuses the same style as terms and conditions screen.
A Privacy Policy Screen
Click Privacy Policy in Register or Login screen, a privacy policy screen shows up with the same content as https://mobilitydata.org/privacy-policy/

feat: 306 create a privacy policy screen

---

.github/workflows/release.yml

**Summary:**
This PR fixes the Github trigger release to only released 
Release workflow should only be triggered after releases are `released`

chore: add released type to release event

---

.github/workflows/api-dev.yml
.github/workflows/db-prod.yml
.github/workflows/db-qa.yml
.github/workflows/integration-tests.yml
.github/workflows/release.yml

**Summary:**
Modified GH actions to upload integration tests logs in case of a failure of the tests. That should help to know what went wrong.
This was asked for in https://github.com/MobilityData/mobility-feed-api/issues/319
Also corrected some typos here and there.
If the integration tests fail during the api deployment the integration tests results should still be uploaded to Github. 
To test this properly we would need to have the API integration tests fail. 
I tested by introducing an artificial error in integration-tests.yml (added an exit 1). But that requires changes to the codebase then push. This can be done in a throwaway branch.

fix: Upload integration tests results if tests fail

---

docker-compose.yaml
web-app/README.md

**Summary:**
When setting up the mobility-feed-api using the readme, I ran into an issue running the command `docker-compose --env-file ./config/.env.local  up -d --force-recreate` where the error was that it couldn't find the changelog.xml. With the help of @davidgamez it was discovered that the file structure changed in liquibase 4.27 and that the solution was to include 'changelog' into the search-path. It was tested on David's machine that this addition did not break the existing functionality
For the addition in the `web-app` if you build the package with `npm install` it will return an error as `react-scripts` seems to not be compatible with the latest typescript (https://github.com/facebook/create-react-app/issues/13080). Installing with `yarn` seems to use smart alternatives to …

fix: onboarding config and readme updates for web-app

---

infra/terraform-init/main.tf

Hotfix for the failing deployment in QA due to the service account not having permission to create a workflow in GCP.

fix: workflow creation permission

---

functions/yarn.lock
web-app/yarn.lock

Sibling of #373
Bumps the npm_and_yarn group with 3 updates in the /functions directory: [express](https://github.com/expressjs/express), [ip](https://github.com/indutny/node-ip) and [jose](https://github.com/panva/jose).
Bumps the npm_and_yarn group with 5 updates in the /web-app directory:
Bumps the npm_and_yarn group with 3 updates in the /functions directory: [express](https://github.com/expressjs/express), [ip](https://github.com/indutny/node-ip) and [jose](https://github.com/panva/jose). Bumps the npm_and_yarn group with 5 updates in the /web-app directory:
| Package | From | To |
| --- | --- | --- |
| [express](https://github.com/expressjs/express) | `4.18.2` | `4.19.2` | | [ip](https://github.com/indutny/node-ip) | `1.1.8` | `1.1.9` | | …

chore(deps): bump the npm_and_yarn group across 2 directories with 6 updates(sibling)

---

api/requirements.txt
api/src/feeds/filters/gtfs_rt_feed_filter.py
api/src/feeds/impl/feeds_api_impl.py
api/src/feeds/impl/models/location_impl.py
api/tests/unittest/models/test_location_impl.py
docs/DatabaseCatalogAPI.yaml
integration-tests/src/endpoints/gtfs_rt_feeds.py
integration-tests/src/endpoints/integration_tests.py
scripts/docker-localdb-rebuild-data.sh

Add location to API response for GTFS Realtime feeds and to the endpoint parameters.
Closes #380 
Locations field is present in endpoints: v1/gtfs_rt_feeds and v1/gtfs_rt_feeds/{feed_id}
- Checkout the branch
- Execute(**Warning your local database content will be deleted**),
```
docker-compose --env-file ./config/.env.local  up -d --force-recreate
scripts/api-gen.sh
scripts/db-gen.sh
```
- Execute,
```
./scripts/api-start.sh
```
- Test the gtfs_rt_feed for individual id endpoint. Example curl command,
```
curl --location 'http://localhost:8080/v1/gtfs_rt_feeds/mdb-1336' \
--header 'Accept: application/json'
```
- Verify that the locations' field is populated
- Test the gtfs_rt_feeds endpoint. Example curl command,
```
curl --location …
```

feat: add location array to gtfs_rt API response

---

functions-python/validation_report_processor/README.md
functions-python/validation_report_processor/src/main.py
functions-python/validation_report_processor/tests/test_validation_report.py
workflows/gtfs_validator_execution.yml

**Summary:**
Closes #401 
This PR updates the naming convention of validation reports to include the validator version. This change affects both HTML, JSON report and `system_errors.json` name formats and the corresponding updates have been made in the database update process to reflect this new naming convention.
**Expected Behavior:**
With the changes introduced in this PR, the filenames for both HTML and JSON validation reports will now include the validator version, ensuring clearer traceability and management of report files across different validator versions.
Database Example:
Below is an example from the `ValidationReport` entity for feed `mdb-101` demonstrating how the reports are named with the validator version included:
| id                                  | validator_version …

feat: added validator version to report filename

---

README.md
api/src/feeds/impl/feeds_api_impl.py
api/tests/test_datasets_api.py

**Summary:**
closes #359 
Removed duplicate locations in the python code.
In the case of feeds with more than one dataset, there should be only one location in response.
eg for the test data, a call to 
```
curl -X 'GET' 'http://localhost:8080/v1/gtfs_feeds/mdb-1' -H 'accept: application/json'
```
should give something like:
```
{
"id": "mdb-1",
"data_type": "gtfs",
"status": "inactive",
...
"locations": [
{
"country_code": "US",
"subdivision_name": "Maine",
"municipality": "Casco Bay"
}
],
"latest_dataset": null
}
```
Tested using the [test data](https://github.com/MobilityData/mobility-feed-api/blob/main/api/tests/test_data/test_datasets.json)
`./scripts/docker-localdb-rebuild-data.sh --populate-db --populate-test-db`
In the test data it so …

fix: Removed duplicate locations returned by gtfs-feeds API call

---

api/src/database/database.py
api/src/scripts/populate_db.py

**Summary:**
SQLAlchemy 2.x added support for many-to-many relations mapping. This is handy for querying the entities as it reduces the amount of independent queries, joins, and columns within the code. While updating and creating entities, it is also possible to leave most of the heavy work to the ORM. However, this comes with some restrictions on the entity types to be used as part of the relationship arrays. This PR refactored the populate script, fixing the incompatibility with 2.x version and using the create/update capabilities offered by SqlAchemy
[Successful execution on DEV](https://github.com/MobilityData/mobility-feed-api/actions/runs/8839115387/job/24271787959)
Fixes #402 
Populate script executes, creates, and updates without issues. …

fix: populate DB is broken after upgrading SQLAlchemy to 2.x version

---

api/src/feeds/impl/feeds_api_impl.py

**Summary:**
Closes #431 
**Bug Explanation:**
The API code was incorrectly filtering out the latest datasets if their corresponding bounding box was `null`. This issue affected all datasets in `QA` before March. However, after March, all the latest datasets had valid bounding boxes. Ideally, this should have been addressed in February following the merge of #247. Nevertheless, the bug is now fixed. The null bounding boxes investigation should be addressed in a separate issue (#434).
**Testing Instructions:**
- Connect the local API to the QA or DEV database to access datasets.
- Test the `gtfs_feeds` endpoint using a feed with the latest dataset, such as `/v1/gtfs_feeds/mdb-1210` in QA.

fix: latest dataset being null

---

.github/workflows/validator-update.yml
infra/functions-python/main.tf
infra/main.tf
infra/terraform-init/main.tf

**Summary:**
Closes [issue #1746](https://github.com/MobilityData/gtfs-validator/issues/1746). This PR introduces functionality to run an update of the validation report when the GTFS Canonical Validator Web Services are updated.
**Expected Behavior:**
- When the staging environment of the web services is updated, a Cloud Task is created in the `dev` project within the `update-validation-report` queue, set to run 24 hours after the trigger.
- When the GTFS Validator is released, the same process is followed in the production environment.
Working example from `dev`:

feat: Modify Mobility Database workflow so when new validator version is released, run the validator on all latest datasets

---

api/src/database/database.py
api/src/feeds/impl/feeds_api_impl.py
api/src/feeds/impl/models/basic_feed_impl.py
api/src/feeds/impl/models/bounding_box_impl.py
api/src/feeds/impl/models/external_id_impl.py
api/src/feeds/impl/models/gtfs_feed_impl.py
api/src/feeds/impl/models/redirect_impl.py
api/tests/test_database.py
api/tests/test_feeds_api.py
api/tests/test_utils/database.py
api/tests/unittest/models/test_basic_feed_impl.py
api/tests/unittest/models/test_external_id_impl.py
api/tests/unittest/models/test_gtfs_feed_impl.py
api/tests/unittest/models/test_redirect_id_impl.py
api/tests/unittest/test_feeds.py
docs/DatabaseCatalogAPI.yaml
scripts/docker-localdb-rebuild-data.sh

This PR fixes the limit and offsets issues for endpoints `feeds`. The _"previous"_ implementation uses joins to bring entities from related tables. As there are a couple of x-to-many relations, the resulting data contained multiple rows from the same feed. Example datasets, locations, and redirects. One solution explorer was to apply limits and offsets in memory, but it was discarded due to the inefficiency of loading data upfront and making it hard to apply sorting. 
The solution proposed in the PR removes the need for joins, as Alchemy 2.x will do the join and load data when necessary. This makes the implementation simpler, see snipped below to follow a general pattern:
```python
feed_filter = FeedFilter(status=status, provider__ilike=provider, producer_url__ilike=producer_url) …
```

fix: default sort isn't by mdb-id + limit intermittently works

---

web-app/src/app/components/Header.tsx
web-app/src/app/constants/Navigation.spec.ts
web-app/src/app/constants/Navigation.ts
web-app/src/app/interface/Navigation.ts
web-app/src/app/interface/RemoteConfig.ts

closes #477 
**Summary:**
Adds feature flag to 'feeds' page to hide it in PROD until it's ready
If the feature flag is disabled, 'feeds' should not appear in the nav bar, nor should it exist as a route.
Go into [firebase](https://console.firebase.google.com/project/mobility-feeds-dev/config/env/firebase) and modify the feature flag values
Go into `web-app/src/app/constants/Navigation.ts` and manually modify the feature flag values
- [] Add or update any needed documentation to the repo

fix: feature flag 'feeds' page

---

README.md
api/tests/unittest/test_feeds.py
scripts/docker-localdb-rebuild-data.sh

**Summary:**
Closes #440 
Tested the conditions that lead to #431 
These tests pass: 
- https://github.com/MobilityData/mobility-feed-api/blob/8eee5c90fad8c275bc0e7a947d565c847b189d0c/api/tests/unittest/test_feeds.py#L114
- https://github.com/MobilityData/mobility-feed-api/blob/8ebbffeebcccc994deb347de40dff83968c3506b/api/tests/unittest/test_feeds.py#L199
To test I put back the code from [PR #433](https://github.com/MobilityData/mobility-feed-api/pull/433/files) in api/src/feeds/impl/feeds_api_impl.py and verified that it failed.

fix: Test latest_dataset is not none when bounding_box is None

---

functions-python/batch_process_dataset/src/main.py
functions-python/batch_process_dataset/tests/test_batch_process_dataset_main.py
functions-python/helpers/utils.py

**Summary:**
This update enhances batch processing by validating that the producer URL returns a zipped file before saving to GCP and updating the database. As part of this improvement, I also removed from GCP and the database all datasets and related entities that were not zipped files and not linked to other records. Below are the details of all invalid datasets per environment:
- [invalid_datasets_prod.csv](https://github.com/user-attachments/files/15904126/invalid_datasets_prod.csv) $\approx$ 25% of all 8609 datasets are invalid zips.
- [invalid_datasets_dev.csv](https://github.com/user-attachments/files/15904125/invalid_datasets_dev.csv)
- [invalid_datasets_qa.csv](https://github.com/user-attachments/files/15904127/invalid_datasets_qa.csv)
**Expected Behavior:**
The system should …

feat: validate downloaded files as ZIP before processing dataset

---

functions-python/helpers/database.py
functions-python/helpers/tests/test_database.py

**Summary:**
After upgrading to the Alchemy 2.0 plain text SQL queries need to be wrapped with `text` function. This is for security and validation purposes.
The refresh materialized view function works as expected.
Unit tests should cover the right behavior. For manual testing you need to deploy the bash processing code to DEV and run it. Expect no error in the logs with message: _"Error raised while refreshing view: feedsearch"_

fix: refresh materialized view in batch functions

---

functions-python/helpers/tests/test_helpers.py
functions-python/helpers/utils.py

**Summary:**
Added `User-Agent` to the header of the requests, resolving the issue for all feeds specified in #502. To achieve this, I mimicked the equivalent curl request from the browser network tab and systematically filtered out each header to identify that only the `User-Agent` was necessary.
**Testing Tips:**
- Run `datasets-batch-deployer-dev` from the branch `feat/502` to deploy the current behavior.
- Adjust the `FEEDS_LIMIT` variable in the `batch-datasets-dev` cloud function to cover more feeds.
- Filter logs to validate that feeds `mdb-232`, `mdb-919`, and `mdb-683` have been properly processed. If these feeds are not included in the processing, you may need to further increase the `FEEDS_LIMIT` variable.
**Example for `mdb-683`**:
Please make sure these boxes are checked …

feat: Programmatic download of valid ZIP files returns HTML responses for certain producer URLs

---

.github/workflows/integration-tests.yml
api/.gitignore
api/src/feeds/impl/metadata_api_impl.py
api/tests/test_metadata_api.py
integration-tests/src/endpoints/metadata.py

**Summary:**
This update introduces automated tests to verify the expected behavior of the commit hash and version returned from the `metadata` endpoint.
**Expected Behavior:**
- The unit test `test_metadata_get` ensures that the version is correctly read from the `api/src/version_info` file.
- The integration test `test_metadata` confirms that the version and commit hash returned by the endpoint match those generated by the `./scripts/extract-hash-and-version.sh` script, as part of the `integration-tests.yml` action.
**Testing Instructions:**
1. **Prepare the Environment:**
- Copy the content of the QA `version_info` file to `api/src/version_info`:
```
[DEFAULT]
LONG_COMMIT_HASH=2c67dc67ea3a029f498349e8fb8571a9a53bcaee
SHORT_COMMIT_HASH=2c67dc67e
EXTRACTED_VERSION=v1.2.1_SNAPSHOT
```
2. …

feat: verify if the version and commit hash are accurate

---

web-app/src/app/components/ContentBox.tsx
web-app/src/app/components/WarningContentBox.tsx
web-app/src/app/screens/Feed/DataQualitySummary.tsx
web-app/src/app/screens/Feed/PreviousDatasets.tsx
web-app/src/app/screens/Feed/index.tsx

closes: #535 
**Summary:**
Handle the `undefined` or `null` states in the Feed page as well as styling the warning component
1. If a feed doesn't have bounding box data, show warning
2. If a feed doesn't have data quality report, show warning
3. If a feed doesn't have datasets, show warning + hide previous
4. If a feed dataset doesn't have data quality report, show action 
Go to the specified feed ids and view warnings
Feed ids to test
[No bounding box + no data quality report + no datasets]: mdb-1838 (SEMO)
[Deprecated Feed]: mdb-273 (Ben Franklin Transit) deprecated 
[Dataset missing data quality]: mdb-2024 (Ben Franklin Transit)

feat: null states for feed page

---

api/src/feeds/impl/feeds_api_impl.py
api/src/feeds/impl/models/basic_feed_impl.py
api/tests/unittest/test_feeds.py
integration-tests/src/endpoints/datasets.py
integration-tests/src/endpoints/integration_tests.py

**Summary:**
- **Fixed Failing Integration Tests:**
- Implemented an outer join for the `location` and `feed` entities to ensure proper data fetching.
- Added `joinedload` for all entities accessed by the `from_orm` methods to optimize query performance and reduce additional database queries. For instance, querying `https://api-qa.mobilitydatabase.org/v1/gtfs_feeds` now takes approximately 1.6 seconds, down from 17 seconds.
- Removed the unnecessary test for the validity of the latest URL, as this validation is already handled within the data pipeline. Performing this test within the integration tests is redundant and not the most appropriate place for it.
[Example of successful execution](https://github.com/MobilityData/mobility-feed-api/actions/runs/9863354004/job/27236236214)
Please …

fix: failing integration tests 

---

web-app/src/app/screens/Home.tsx

**Summary:**
Should close what's left of #347 
- makes a Search box available on home page
- navigates to `/feeds?q=<search query>` w/ search text contents 
- type in search query and press "enter" key or click "search" button

feat: add search box to home page

---

web-app/public/locales/en/common.json
web-app/src/app/screens/Feeds/GtfsRtEntities.tsx
web-app/src/app/screens/Feeds/SearchTable.tsx

closes #541 
**Summary:**
Add indicators in the search page for GTFS RT to display which entities are available
Display the available gtfs rt entitites with a tool tip
Search feeds and see if the correct icons show up

feat: gtfs rt entity icons in search page

---

web-app/src/app/screens/Feed/index.tsx

closes #547 
**Summary:**
When a feed doesn't have a dataset but has a redirect link, it should only show the redirect link warning and not both
Above^
Go on feeds with redirect links and no datasets and make sure only 1 warning appears
ex: mdb-1030

Feat: Feed page remove duplicate warnings (no dataset and redirect link)

---

api/src/feeds/impl/models/basic_feed_impl.py
api/src/scripts/populate_db.py
api/src/scripts/populate_db_test_data.py
api/tests/unittest/test_feeds.py
docs/DatabaseCatalogAPI.yaml
liquibase/changelog.xml
liquibase/changes/feat_533.sql

**Summary:**
Closes [#533](https://github.com/MobilityData/mobility-feed-api/issues/533) by adding the `created_at` field to the responses of the basic feed, GTFS feed, and GTFS-RT feed. 
**Expected behavior:**
The `created_at` field should appear in the API responses for the basic feed, GTFS feed, and GTFS-RT feed. The field should contain a timestamp indicating when the feed was created.
Example response:
```json
{
"id": "mdb-195",
"data_type": "gtfs",
"status": "active",
"created_at": "2024-07-11T15:24:16.631817Z",
// other existing fields
}
```
- Run the API locally to ensure the changes are correctly integrated.
- Verify that the `created_at` field is present in the responses for the basic feed, GTFS feed, and GTFS-RT feed.
- Check that the `created_at` field …

feat: add created_at timestamp to feed response

---

.github/workflows/integration-tests-pr.yml
integration-tests/src/endpoints/datasets.py
integration-tests/src/endpoints/integration_tests.py
scripts/integration-tests.sh
scripts/lint-write.sh

**Summary:**
- Added a GitHub Action that connects the local API to the QA database to run integration tests.
- Introduced a `DATASETS_LIMIT` environment variable to limit the number of datasets tested. This is set to 25 for local integration tests.

feat: run integration tests on PR

---

web-app/cypress/e2e/feeds.cy.ts
web-app/cypress/fixtures/feed_datasets_test-516.json
web-app/cypress/fixtures/feed_test-516.json
web-app/cypress/fixtures/gtfs_feed_test-516.json

**Summary:**
Add cypress intercepts for feed API calls.
I tried to use the _cy. fixtures_ command from Cypress, but its asynchronous nature makes the code less readable. This is why I used a regular JSON import for the fixtures. 

chore: add cypress intercepts for feed api calls

---

api/src/feeds/impl/feeds_api_impl.py
api/tests/integration/test_datasets_api.py

**Summary:**
Closes #600 
Applies to `/v1/gtfs_feeds/{id}/datasets` endpoint
Checked for the existence of a feed before trying to extract its datasets.
If the feed does not exist it should return 404
If the feed does exist but has no datasets, it should return 200 with an empty list.

fix: returned 404 if feed does not exist

---

web-app/src/app/screens/Feed/FeedSummary.tsx

**Summary:**
Closes #601 
Replace Download button on GTFS pages with a hyperlink
Click on the producer url hyperlink opens a new tab

fix: Replaced Download button on GTFS pages with a hyperlink

---

api/src/feeds/impl/metadata_api_impl.py

**Summary:**
Fixes #639 
I'm reverting changes in PR #585 as the metadata endpoint returned `null` in the version and commit_hash. The previous code is still relevant; we only add the `src` suffix when the folder ends in `API`; otherwise, the file is on the "relative" root of the source.
Health check passed [here](https://github.com/MobilityData/mobility-feed-api/actions/runs/10184295233/job/28171640163)
This PR was deployed to QA for testing, and the endpoint result is as expected:
```
{
"version": "v1.2.1_SNAPSHOT",
"commit_hash": "dce5fc44517f8228d04ec5e08ec7a47b251a390a"
}
```
The deployed endpoint return the proper version and commit hash values.
The only way to test it is to deploy it in a real environment. 
Test in QA
- Grab an access token …

fix: revert changes in metadata api endpoint

---

.github/workflows/db-update-prod.yml

**Summary:**
Release GH action is failing due to differences between the code version and the target environment. 
Example of failing action, [here](https://github.com/MobilityData/mobility-feed-api/actions/runs/10184766911/job/28173237980).
Release GH action runs, ignoring integration tests in QA and PROD for DB Update action.
Create a release...

fix(build): Executing integration tests on Qa and PROD in db update only for repository dispatch

---

web-app/src/app/screens/Feed/FeedSummary.tsx
web-app/src/app/screens/Feed/index.tsx

**Summary:**
Closes #602 
Remove "Authentication Info" link at the top of the page
When the authentication type is not 0 (so either 1 or 2), display the associated auth type (API Key or HTTP Header) with a link to the authentication info link in the Register button
mdb-1636

feat: Remove "Authentication Info" link at the top of the page

---

web-app/src/app/screens/Feeds/index.tsx

**Summary:**
Closes #649 
update the URL query params only when the search action is dispatched, rather than with each character typed.
search for new york in feeds screen, click back navigation button in the browser, it goes back to the previous page instead of  removing the previous keystroke.

fix: 649 search screen back and forward browsers actions reacting on typying

---

web-app/src/app/screens/Feeds/index.tsx

**Summary:**
Closes #667 
When a user searches for California and then searches for New York, returning to the previous page should display the search results for California.
goto feeds page and search for California, click page 2
do a new search for New York
click on back navigation button of browser
returning to the previous page should display the search results for California page 2

fix: 667 back navigation should also show previous search result

---

.github/workflows/db-update-prod.yml
.github/workflows/integration-tests.yml
integration-tests/src/endpoints/integration_tests.py
integration-tests/src/endpoints/metadata.py
integration-tests/src/main.py
scripts/integration-tests.sh

**Summary:**
closes #655
- Added code to exclude classes from integration test. 
- Modified integration test action so we exclude the metadata tests if the trigger is catalog-sources-updated, i.e. it comes from the mobility_database_repo.
- We still want to keep the health check in all cases (it yells us if we can talk to the API at least). Separated metadata tests into basic and normal. 
- The basic just make sure the API values returned have the right format.
Integration should not fail for no good reason.
- Ran integration-test.sh locally with the -x or -c arguments
- e.g. ./scripts/integration-tests.sh -u http://0.0.0.0:8080 -f "$FILE_PATH" -x MetadataEndpointTests
- check in the output that MetadataEndpointTests is not run.
I also tested with …

fix: Modified to not run the full metadata tests in some circumstances

---

.github/workflows/db-update-prod.yml
.github/workflows/integration-tests.yml

**Summary:**
While looking at the action logs from #673, I noticed that `MetadataEndpointTests` was not run.
This should happens only with the trigger is `repository_dispatch`
MetadataEndpointTests should run in the Health Check after a PR merge.

fix: integration tests is blocking catalog update in prod - correction

---

web-app/cypress/e2e/changepassword.cy.ts

**Summary:**
As mentioned in #458, the cypress change password test fails intermittently. 
This PR just changes the test to issue a warning if this happens and not fail the test.
**This should be removed once #458 is solved**
Most of the time the test passes. 
Once in a while a warning is issued
Since it's hard to reproduce, just made sure the test works if the change password error works, meaning it's not worse than original.

chore: Do not fail cypress test if the change password fails

---

web-app/package.json
web-app/src/app/screens/Feed/FeedSummary.tsx
web-app/src/app/screens/Feeds/SearchTable.tsx
web-app/src/app/services/feeds/utils.spec.ts
web-app/src/app/services/feeds/utils.ts
web-app/src/app/types.ts
web-app/yarn.lock

closes #647 
**Summary:**
Format the new country data as shown in the screenshots
Location data should be shown as: 🇨🇦 Canada | 🇺🇸 United States
Go on the search page and see if the location data is shown as above. TIP: Spain is a good search for many countries

Feat: 647 display multiple countries format

---

web-app/package.json
web-app/src/app/screens/Account.tsx
web-app/src/app/screens/Contribute.tsx
web-app/src/app/screens/Feed/PreviousDatasets.tsx
web-app/src/app/screens/FeedSubmission/FeedSubmissionStepper.tsx
web-app/src/app/screens/FeedSubmission/Form/index.tsx
web-app/src/app/screens/FeedSubmission/index.tsx
web-app/src/app/screens/FeedSubmissionFAQ.tsx
web-app/src/app/screens/Home.tsx
web-app/src/app/screens/LegacyHome.tsx
web-app/src/app/store/dataset-selectors.ts
web-app/yarn.lock

**Summary:**
- Fixed console.errors / warnings (many of them were due to DOM html element violations)
- Added number animation on home page
- Fixed some styling on home page
NOTE: 
1. Looked at adding "open in new tab" to table row in search feeds. Its a little complicated due to element violations while using an `a` tag. Would have to be re-looked at
2. Not all console.errors were solved
App should work as normal
See if the numbers animation works on home page + nothing else is broken

fix: console errors + warning. Numbers animation home. Home style fix

---

web-app/src/app/screens/SignIn.tsx

closes #693 
**Summary:**
When registering an account, sometimes the verification email would not send until "Send again" was clicked
When the user registers for an account and it's through Github or Email, it should send the validation email without further action
Create an account using any provider. Github and Email will ask you to verify email so ideal to use those. Once account is created, check if you got validation email.
**Reason for bug**
This bug exists because you can make an account through the sign-in page through the third party apps. Sign-in page doesn't dispatch email. Google and Apple do not verify email

Fix: dispatch email on newly created account to verified email

---

integration-tests/src/endpoints/metadata.py

**Summary:**
Metadata integration test was too restrictive when checking the format of the version. Now it will accept any suffix (including _RC1)

Made the version verification more lax in integration tests

---

api/src/feeds/impl/models/basic_feed_impl.py
api/src/feeds/impl/models/search_feed_item_result_impl.py
api/tests/unittest/models/test_search_feed_item_result_impl.py

**Summary:**
Added conditionals and protecting code to handle cases for missing locations, missing country and invalid country code.
The search endpoint returns all GTFS and GTFS-rt feeds when no parameters are passed.
- Setup local API environment
- Query the search endpoint by passing an empty search. Example:
```
curl --location 'https://api-qa.mobilitydatabase.org//v1/search?search_query=' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer REPLACE_ME_WITH_ACCESS_TOKEN'
```

fix: empty search query with no additional parameter returns HTTP 500

---

api/src/scripts/populate_db_gtfs.py
api/tests/test_utils/database.py

**Summary:**
Closes #694 
Added code to set the country in the populate script. This will work only for new entries
For old entries, added a post-processing operation in the populate script that looks at all the location table entries and adds the country if it's missing. The country is obtained from the country code already in the table entry.
All locations should now have a country if the country code has a corresponding country
Tested locally with a location table on which I set all countries to null. Test that the post processing sets the countries properly.
Tested also by deleting the DB and rerun the populate script. The countries should also be set properly as they are considered new entries.
Please make sure these boxes are checked before …

fix: Set the country if missing from DB in the populate script

---

functions-python/batch_process_dataset/src/main.py
functions-python/batch_process_dataset/tests/test_batch_process_dataset_main.py

**Summary:**
Fix a misspelling in the feeds credentials variable name that blocks authenticated feeds from being downloaded.
Authenticated feeds are downloaded.
Tested on DEV environment, [here an example of an authenticated feed downloaded](https://mobility-feeds-dev--pr-699-7543h9pe.web.app/feeds/mdb-1847)
Successfully trace of a dataset updated, [here](https://console.cloud.google.com/logs/query;query=resource.type%20%3D%20%22cloud_run_revision%22%0Aresource.labels.service_name%20%3D%20%22batch-process-dataset-dev%22%0Aresource.labels.location%20%3D%20%22northamerica-northeast1%22%0Aseverity%3E%3DDEFAULT%0Atrace%3D%22projects%2Fmobility-feeds-dev%2Ftraces%2Ff9847126d2276a247670d5b3896641ab%22;storageScope=project;cursorTimestamp=2024-08-20T23:50 …

fix: fix invalid feeds credentials variable name

---

web-app/src/app/screens/Analytics/GTFSFeedAnalytics/GTFSFeedAnalyticsTable.tsx

**Summary:**
Hotfix for the default behaviour of the location filter for the GTFS metrics

hotfix: default filtering for location

---

web-app/src/app/components/Header.tsx

**Summary:**
BUG
When navigating from the header it would be relative paths ex
`https://mobilitydatabase.org/feeds`-> click header FAQ -> `https://mobilitydatabase.org/feeds/faq`
FIX
`https://mobilitydatabase.org/feeds`-> click header FAQ -> `https://mobilitydatabase.org/faq`
`https://mobilitydatabase.org/feeds`-> click header FAQ -> `https://mobilitydatabase.org/faq`
Navigate from anywhere using header

navigation fix

---

api/tests/integration/test_feeds_api.py

closes #539 
**Summary:**
The pagination functionality of the datasets endpoint existed already, this PR only introduces supporting tests
The tests pass
run the tests

feat: dataset pagination tests

---

README.md
functions-python/README.md
scripts/docker-localdb-rebuild-data.sh

**Summary:**
As docker 20.10 `docker-compose` has been replaced by `docker compose` command. This PR replace the use of the legacy command.
The changes in the build script don't impact the python functions deployment.
- Upgrade your local docker to +=20.10
- Execute 
```
./scripts/docker-localdb-rebuild-data.sh
```
- Verify that the local docker DB is correctly updated.

chore: replace docker-compose by docker-compose

---

.github/workflows/datasets-batch-deployer.yml
functions-python/batch_datasets/main_local_debug.py
functions-python/batch_datasets/requirements.txt
functions-python/batch_datasets/src/main.py
functions-python/batch_process_dataset/.env.rename_me
functions-python/batch_process_dataset/main_local_debug.py
functions-python/batch_process_dataset/requirements.txt
functions-python/batch_process_dataset/requirements_dev.txt
functions-python/big_query_ingestion/requirements.txt
functions-python/extract_location/requirements.txt
functions-python/gbfs_validator/requirements.txt
functions-python/preprocessed_analytics/requirements.txt
functions-python/update_validation_report/requirements.txt
functions-python/validation_report_processor/requirements.txt
functions-python/validation_to_ndjson/requirements.txt
functions/firebase.json
infra/batch/vars.tf
infra/functions-python/vars.tf
infra/metrics/vars.tf

**Summary:**
- Upgrade Python functions to 3.11 runtime to align with the DB API. 
- Re-organized dependencies to prepare future refactoring to have a base requirements file for all GCP functions.
- Upgrade Firebase runtime functions to Node 20
- Tested in DEV environment
- Python functions runtime must be in the 3.11 version
- Firebase functions runtime must be in the 20 version.
- Upgrade your local environment to Python 3.11
- Make sure all tests pass locally
- Run functions and execute them locally or in DEV environment

chore: upgrade python packages in functions and set runtime to python 3.11 - Firebase functions runtime to Node 20

---

web-app/.eslintrc.json
web-app/cypress/e2e/addFeedForm.cy.ts
web-app/public/locales/en/feeds.json
web-app/src/app/screens/FeedSubmission/Form/FirstStep.tsx
web-app/src/app/screens/FeedSubmission/Form/FourthStep.tsx
web-app/src/app/screens/FeedSubmission/Form/SecondStep.tsx
web-app/src/app/screens/FeedSubmission/Form/SecondStepRealtime.tsx
web-app/src/app/screens/FeedSubmission/Form/ThirdStep.tsx
web-app/src/app/screens/FeedSubmission/Form/components/FormLabelDescription.tsx
web-app/src/app/services/feeds/utils.spec.ts
web-app/src/app/services/feeds/utils.ts

closes #748 
**Summary:**
Changes
- URL Validation added to: auth sign up link, old feed link, license path, all gtfs rt links (including old)
- Data producer is now optional
- Form label description styling updated for uniformity
- validating feed links now accept uppercase
- eslint rule updated
All changes from https://github.com/MobilityData/mobility-feed-api/issues/748 should be addressed
Go to the add feed form, and verify the ticket changes in https://github.com/MobilityData/mobility-feed-api/issues/748 and assure they work

Feat: 748 add feed form minor changes

---

.github/workflows/web-app-deployer.yml
.github/workflows/web-dev.yml
.github/workflows/web-pr.yml
.github/workflows/web-prod.yml
.github/workflows/web-qa.yml
functions/packages/feed-form/package.json
functions/packages/feed-form/src/impl/feed-form-impl.ts
functions/yarn.lock

closes #763 
**Summary:**
When the add feed form successfully adds a feed to the correct google sheet, it will send out a slack notification
When in DEV as a feed is added through the form, it should send a notification to the slack channel #slack-test-channel (private channel)
When in PROD the channel will be #internal-add-feeds
Submit a test form with the preview url and you should see a notification in the #slack-test-channel
**Notes**
Because we have a lot of control we can add high level information to the slack notification ex: GTFS or GTFS RT, is it from official producer, etc. Data that would be useful at a quick glance

feat: slack notification on add feed form

---

.github/workflows/web-app-deployer.yml
.github/workflows/web-prod.yml
functions/packages/feed-form/src/__tests__/github-issue-builder.spec.ts
functions/packages/feed-form/src/impl/feed-form-impl.ts
functions/packages/feed-form/src/impl/types.ts

closes #764 
**Summary:**
Create a github issue when a new feed is submitted / updated
When a new / updated feed is submitted (in production) a github issue will be created. That github issue will be linked in the slack notification as well
Will need to be tested in production
- [X Linked all relevant issues

Feat: create github issue on new add feed form

---

bigquery/compare-validation-reports.sql
infra/metrics/main.tf

**Summary:**
This PR introduces a new BigQuery function and updates the infrastructure to enable comparison of validation reports between two specified versions.
- **[`bigquery/compare-validation-reports.sql`](diffhunk://#diff-12e7d8893d913364357a469a83a00431fc1a7d0ba73935e1b0aaf378d73ac3c5R1-R93)**: Added a new function, `compare_validation_reports`, designed to compare validation reports between a previous and a current version. This procedure generates a merged report highlighting the differences in validation notices, including new and dropped notices.
- **[`infra/metrics/main.tf`](diffhunk://#diff-c4e8cb223e8b8ff846332198c8ca30c5f829ddafc0e02fbf31ca19e07e064ae2R528-R548)**: Updated Terraform configuration to include a new BigQuery routine resource, `compare_validation_reports`. This …

feat: big query procedure for comparing validator versions

---

web-app/src/app/screens/Feed/FeedSummary.tsx
web-app/src/app/utils/consts.ts

closes #733 
**Summary:**
Update the Feature keys and links in the frontend to reflect the upcoming validator 6.0 release while also supporting previous versions
When going to the feed detail page of any feed, under the "Feature" section, you should be able to click on any of them and it will direct you to the correct gtfs.org page
Go to any feed detail page, when you click on a feature make sure it maps correctly based on https://github.com/MobilityData/gtfs-validator/blob/master/docs/FEATURES.md 
For the deprecated features (as of 6.0) they should navigate to the corresponding updated feature page

Feat: update features for validator 6.0

---

web-app/src/app/screens/FeedSubmission/index.tsx

closes #775 
**Summary:**
On new add feed form, when clicking 'faq' it should open in new tab
On new add feed form, when clicking 'faq' it should open in new tab
GO to new add feed form and click the faq at the top. Should open in new tab

fix: add feed faq is external link

---

web-app/src/app/context/RemoteConfigProvider.spec.tsx
web-app/src/app/context/RemoteConfigProvider.tsx
web-app/src/app/interface/RemoteConfig.ts

closes #767 
**Summary:**
In an effort to test in PROD without testing in PROD, this PR introduces a remote config to allow certain emails to access all the feature flags even if they are diabled
In the remote config, the values of `bypassFeatureFlag` you can put your email (or a regex) and with that email you will be able to access all feature flags (boolean) regardless of what their value is set as
Add your email to the regex value in the remote config for DEV, sign in with that email, and in the header you should see the translation selection in the top right. (that feature is currently false on all environments)
When the email signed in is included in the …

Feat:feature bypass

---

web-app/src/app/utils/consts.ts

**Summary:**
The feature urls changed to no longer have `_` and being replaced with `-`. Also fixed the spelling of `In-station Traversal Time`
All features on the feed detail page should go to the correct gtfs.org page
Go to any feed detail page and test if the features navigate correctly

fix: feature url changes

---

web-app/public/locales/en/contactUs.json
web-app/src/app/constants/Navigation.ts
web-app/src/app/router/Router.tsx
web-app/src/app/screens/ContactUs.tsx
web-app/src/i18n.ts

closes #619 
**Summary:**
Adds 'Contact Us' page to the mobility database
When you go on the contact us page, it should be responsive, and all the buttons and links should go / do their expected action 
In the Header, 'contact us' should go to new contact us page
Go on the 'Contact Us' page and click on all the links to make sure the are working correctly. Also make sure the navigation in the header works correctly

feat: contact us page

---

web-app/src/app/services/feeds/utils.ts

**Summary:**
Fix  #799
Having null values in locations don't crash the app.
Follow steps in #799

fix: add null protection for locations field

---

.github/workflows/validator-update.yml

**Summary:**
Closes #785 
This pull request includes a small change to the `.github/workflows/validator-update.yml` file. The change corrects the queue name format and adds a location variable to the `gcloud tasks create-http-task` command.
* Corrected queue name format from `update_validation_report_task_queue` to `update-validation-report-task-queue`.
* Added `--location` parameter to the `gcloud tasks create-http-task` command.
The task queue is successfully created.
Example for [this action run](https://github.com/MobilityData/mobility-feed-api/actions/runs/11709898669/job/32614935602): [update-validation-report-task-queue](https://console.cloud.google.com/cloudtasks/queue/northamerica-northeast1/update-validation-report-task-queue?project=mobility-feeds-prod) …

feat: fix task queue trigger for updating reports post release

---

web-app/.eslintrc.json
web-app/public/index.html
web-app/src/app/screens/About.tsx
web-app/src/app/screens/Contribute.tsx
web-app/src/app/screens/FAQ.tsx
web-app/src/app/screens/Feed/FeedSummary.tsx
web-app/src/app/screens/Feed/PreviousDatasets.tsx
web-app/src/app/screens/Feed/index.tsx
web-app/src/app/screens/Feeds/index.tsx
web-app/src/app/screens/Feeds/styles.tsx
web-app/src/app/screens/Home.tsx
web-app/src/app/screens/LegacyHome.tsx
web-app/src/app/screens/SignIn.tsx
web-app/src/app/screens/SignUp.tsx
web-app/src/app/styles/SignUp.css

**Summary:**
Various small adjustments in the Web-App
Sign-In page
- Button hover styling fix
Feed Detail page
- Bug fix: tld-823 blank fix (null / undefined check)
- Button usability fix (better clicking)
Home page
- text update: 2000 -> 3000 feeds
Feeds search page
- Feature filter is now default closed
- Search bar is now sticky when scrolling down
- Bug fix: selecting features / data type and clicking "back" in browser
General
- Added description to website
On feeds page when scrolling down the search bar should be sticky. Also back navigation when feature selecting should be working as well
1. Go to `tld` feeds ex `feeds/tld-823` and see the page working
2. Test out feeds page url navigation + clicking back
3. On feeds page scroll down and …

Fix: various adjustments

---

api/src/feeds/impl/models/basic_feed_impl.py
docs/DatabaseCatalogAPI.yaml
liquibase/changelog.xml
liquibase/changes/feat_871.sql
liquibase/changes/official_tag_update.sql
web-app/cypress/e2e/feeds.cy.ts
web-app/public/locales/en/common.json
web-app/public/locales/en/feeds.json
web-app/src/app/components/ContentBox.tsx
web-app/src/app/components/Header.style.ts
web-app/src/app/components/Header.tsx
web-app/src/app/interface/RemoteConfig.ts
web-app/src/app/screens/Feed/DataQualitySummary.tsx
web-app/src/app/screens/Feed/Feed.styles.ts
web-app/src/app/screens/Feed/FeedSummary.tsx
web-app/src/app/screens/Feed/index.tsx
web-app/src/app/screens/Feeds/Feeds.styles.ts
web-app/src/app/screens/Feeds/SearchTable.tsx
web-app/src/app/screens/Feeds/index.tsx
web-app/src/app/services/feeds/types.ts
web-app/src/app/styles/VerificationBadge.styles.ts

closes #788 
closes #871 
**Summary:**
Feeds Search Page
- "Is official" badge added on search table
- Wording added when no feeds are found "Try and change search filters"
- Ability to filter by official feed [BEHIND FEATURE FLAG]
Feed Detail Page
- Quality report moved to top of the page -> Chips are now clickable and can go to quality report
- Icons added to buttons and labels
- Map visual is larger
- Official Feed Chip added + timestamp
Styling Fixes
- Discovered a weird interaction when passing a style to an `Sx` prop. When you pass and `Sx` prop with other styles, it's required to manually pass the theme object. If it's just the `Sx` prop then there is no need to pass the theme object. 
On the Feeds search page, you should be able to see a badge for verified …

feat: is official badge + feed detail enhance

---

api/src/feeds/impl/models/gtfs_dataset_impl.py
api/src/feeds/impl/models/latest_dataset_impl.py
api/src/feeds/impl/models/search_feed_item_result_impl.py
api/tests/test_data/extra_test_data.json
api/tests/test_data/test_datasets.json
api/tests/unittest/models/test_basic_feed_impl.py
api/tests/unittest/models/test_gtfs_dataset_impl.py
api/tests/unittest/models/test_gtfs_feed_impl.py
api/tests/unittest/models/test_latest_dataset_impl.py
api/tests/unittest/models/test_search_feed_item_result_impl.py
docker-compose.yaml
docs/DatabaseCatalogAPI.yaml
liquibase/changelog.xml
liquibase/changes/feat_880.sql
liquibase/changes/feat_880_2.sql
web-app/src/app/services/feeds/types.ts

closes #880 
**Summary:**
Added `service_date_range_start` and `service_date_range_end` to the gtfs datasets schema and exposed it in the endpoints
- /v1/gtfs_feeds/{id} (latest_dataset)
- /v1/gtfs_feeds (latest_dataset)
- /v1/datasets/gtfs/{id}
- /v1/gtfs_feeds/{id}/datasets
When calling any of the above endpoints, `service_date_range_start` and `service_date_range_end` should be exposed, unless latest_dataset is null for some of them
Call any of the endpoints and you should see the property exposed. They will all have `null` values

feat: add service date range to schema + expose on endpoints

---

functions-python/validation_report_processor/function_config.json
infra/functions-python/main.tf
infra/main.tf
infra/workflows/main.tf
infra/workflows/vars.tf
workflows/gtfs_validator_execution.yml

**Summary:**
This PR adds a cloud task to the infrastructure to handle tasks that can be executed within two hours and has a rate of 8 concurrent requests. The call from the gtfs_validator_execution workflow to the process-validation-report function is wrapped with the added cloud task.
Closes #863 #875 
Out of scope: set limits in all cloud functions as described [here](https://mobilitydata.notion.site/DB-Connections-Distribution-17d6e644546a80269e10f66f4cb2cb59). This will be done in a follow-up issue.
This pull request includes several changes to the infrastructure and workflow configurations to improve the handling of cloud tasks and permissions. The most important changes include adding new resources for cloud task queues, updating IAM permissions, and modifying the workflow for task …

fix: mitigate 429 errors in cloud function execution for validation reports

---

web-app/public/locales/en/feeds.json
web-app/src/app/components/FeedStatus.tsx
web-app/src/app/screens/Feed/DataQualitySummary.tsx
web-app/src/app/screens/Feed/FeedSummary.tsx
web-app/src/app/screens/Feed/index.tsx

closes #877 
**Summary:**
Display the feed status in the feed detail page as well as the service date range
Should display the the status in the feed detail page, and the service date range if it exists
Go to any feed page and you should be able to see the feed status at the top
For more intense testing, run db locally and inject service_date_range_start/end into the dataset db and see the service date values in the UI. (At the moment all service date values are empty)

feat: feed status in feed detail page

---

web-app/src/app/screens/Feed/DataQualitySummary.tsx

**Summary:**
Label common.noWarnings had a typo.
The `No warnings` text is properly displayed.
Reproduce the issue in QA:
- Visit https://qa.mobilitydatabase.org/feeds/mdb-606
Fixed DEV environment:
- Visit https://mobility-feeds-dev--pr-890-plswpobw.web.app/feeds/mdb-2049

fix:  no warnings label

---

scripts/tunnel-create.sh

**Summary:**
Add retry loop to DB tunnel creation. This PR adds retries every 5 seconds 12 times for a maximum waiting time of 60 seconds.
Fixes #825
DB tunnel is consistently created.
Run the tunnel_create.sh against an environment where the bastion is down. This will increase the probability of seeing the retry and success messages at least once.

fix: DB tunnel fails with high frequency

---

api/src/feeds/impl/models/gtfs_dataset_impl.py
api/src/feeds/impl/models/latest_dataset_impl.py
api/src/utils/model_utils.py
api/tests/utils/test_compare_java_versions.py

**Summary:**
This PR adds a protecting logic to the version comparison. Currently, we are comparing Java versions string with a pip version utility that is not 100% compatible. 
Closes #886
The fastest way to test this PR is using a PR that changes the UI deployed to DEV. 
- Open a UI PR, [example](https://mobility-feeds-dev--pr-885-ab13375j.web.app/)
- Open any feed's screen and expect all feed information to be displayed. 
This pull request introduces a new utility function for comparing Java version strings and integrates it into the existing codebase. The most important changes include the creation of …

fix: java version comparison fails

---

api/src/scripts/populate_db_gtfs.py

**Summary:**
This pull request includes a change to the `process_redirects` method in the `api/src/scripts/populate_db_gtfs.py` file. A `try-except` block is added to handle `ValueError` exceptions when converting `mdb_source_id` to a float. This ensures that if the conversion fails, the `mdb_source_id` is stripped and used as-is.
Successful run: https://github.com/MobilityData/mobility-feed-api/actions/runs/13142416339

fix: support redirect as string

---

functions-python/update_feed_status/.coveragerc
functions-python/update_feed_status/.env.rename_me
functions-python/update_feed_status/README.md
functions-python/update_feed_status/function_config.json
functions-python/update_feed_status/requirements.txt
functions-python/update_feed_status/requirements_dev.txt
functions-python/update_feed_status/src/main.py
functions-python/update_feed_status/tests/test_update_feed_status_main.py
infra/functions-python/main.tf
liquibase/changelog.xml
liquibase/changes/feat_879.sql

#879 
**Summary:**
- Python function to update the feed status based on the latest dataset service date range
- Updated the schema so that `Feed.status` enum includes 'future'
When the `/update_feed_status` function is run, it should update all Feeds (excluding status: 'deprecated' and 'development') based on the Feeds latest dataset service date range
**Follow up tickets**
Because timezone tickets are coming up, I figured it would be better to wait until that code goes in and manually test the python function before setting up the google cloud scheduler. The ticket to set up the scheduler has been created
Locally you can run the function
```
./scripts/function-python-run.sh --function_name update_feed_status --build
```
and modify values in the …

Feat: update feed status python function

---

functions-python/README.md
functions-python/helpers/tests/test_transform.py
functions-python/helpers/transform.py
functions-python/process_validation_report/src/main.py
functions-python/process_validation_report/tests/test_validation_report.py

**Summary:**
The process validation report fails when an empty string(`""`) is found on the JSON value. This PR ignores the empty string values from the fields; it also adds a helper method to be used in similar situations.
The process validation report function should account for missing or empty service date fields
This pull request includes several changes to add new functionality and improve the codebase for the `functions-python` project. The most important changes include adding a new helper function `get_nested_value`, updating the `README.md` file with instructions for generating HTML coverage reports, and refactoring the `generate_report_entities` function to use the new helper function.
* [`functions-python/helpers/transform.py`](diffhunk://#diff-54949798e …

fix: process validation report fails when service date fields are empty

---

functions-python/gbfs_validator/src/gbfs_utils.py
functions-python/gbfs_validator/src/main.py
functions-python/gbfs_validator/tests/test_gbfs_utils.py
functions-python/gbfs_validator/tests/test_gbfs_validator.py

**Summary**  
Closes #940  
**Bug Explanation**  
The issue was caused by **detached SQLAlchemy entities** when fetching GBFS feeds. Since we now manage database sessions more strictly (with automatic session closure in `@with_db_session`), the entities returned from `fetch_all_gbfs_feeds` were detached.  
As a result, when trying to access relationships like `gbfsversions` later in the batch function, we encountered a `DetachedInstanceError`.  
**Fix**  
To fix this issue, I explicitly **detach** the instances from the session right after fetching them. Additionally, we need to ensure that all necessary relationships (like `gbfsversions`) are eagerly loaded, so that all needed data is available even after detaching.  
Please make sure these boxes are checked before submitting your pull …

fix: gbfs validator scheduler failure

---

functions-python/backfill_dataset_service_date_range/src/main.py
functions-python/backfill_dataset_service_date_range/tests/test_backfill_dataset_service_date_range_main.py
functions-python/process_validation_report/src/main.py

**Summary:**
In the validation report it's possible that the service date range start is later than the end. This PR will always use the latest date for the end, and the earlier date in the start. 
Affected functions:
- backfill
- validation report processor
The earlier service date range will always be set to start
The latest service date range will always be set to end

fix: service date range order

---

api/src/shared/common/db_utils.py
infra/feed-api/main.tf

**Summary:**
- ✅ Changed database query to load only the latest dataset in `gtfs_feeds` endpoint. The query now takes less than 10 seconds to run and consumes less than 1GB memory when pointing the local api to the prod database.
- ✅ Increased API memory limit
Closes #548

fix: db query and memory limit

---

infra/functions-python/main.tf
infra/functions-python/vars.tf

**Summary:**
Sets up the Google Cloud Scheduler to run the Update_feed_status function once a day at 4am
This is the PR I used as reference: https://github.com/MobilityData/mobility-feed-api/pull/926
Every day at 4am the update feed status python function will be called 

update feed status terraform daily

---

web-app/public/locales/en/common.json
web-app/public/locales/en/feeds.json
web-app/src/app/screens/Feed/Feed.functions.tsx
web-app/src/app/screens/Feed/FeedSummary.tsx
web-app/src/app/screens/Feed/PreviousDatasets.tsx

closes #949 
**Summary:**
Includes the agency timezone in the Feed Detail page and adjusts the time according to the timezone provided (defaults to UTC if no timezone)
Redesign of the Dataset history table to include service date ranges
It should display the agency timezone in the feed detail page if it exists. It should also format the service date range in accordance with the timezone (defaults to UTC)
The datasets history table should also inlcude the service date range, and you can now click on the validation report which will bring you to the html report
Feed with timezone: feeds/gtfs/mdb-2360
Feed with many datasets: feeds/gtfs/mdb-853
otherwise go on many feeds and see if there are any errors or discrepancies 
Please make sure these boxes …

Feat: feed detail page, timezone + dataset service date range

---

api/src/scripts/populate_db.py
api/src/scripts/populate_db_gtfs.py
functions-python/export_csv/src/main.py

**Summary:**
closes #1050 
When populating the DB from the CSV file, we erroneously took an empty is_official cell for a False. 
Now an empty is_official cell of the CSV means do-not-change the value in the DB.
If the CSV contains TRUE or FALSE, the DB value will be updated accordingly.
Tested manually by populating with 2 CSV files. The 1st file just set some TRUE and some FALSE values, and other were left empty.
The 2nd CSV file changed:
- one is_official TRUE to FALSE -> result: value False in DB
- one is_official FALSE to TRUE -> result: valueTrue in DB
- one is_official TRUE to Empty -> result: value stayed True in DB
- one is_official FALSE to Empty -> result: value stayed False in DB
For good measure I had one is_official in the CSV set to …

fix: Now empty is_official value in CSV will not change the DB during populate

---

api/src/feeds/impl/datasets_api_impl.py
api/tests/integration/test_feeds_api.py
docs/DatabaseCatalogAPI.yaml
liquibase/changelog.xml
liquibase/changes/feat_1046.sql
web-app/public/locales/en/feeds.json
web-app/src/app/screens/FAQ.tsx
web-app/src/app/services/feeds/types.ts

**Summary:**
Add order_ by downloaded_at to the datasets resulting list. This PR also updates downloading frequency documentation of the datasets
Closes #1049 
Datasets are ordered by downloaded_at in descending order.
- Checkout branch and run the API locally
-Load data to local DB
```
./scripts/docker-localdb-rebuild-data.sh --populate-db --populate-test-data
```
- Execute
```
curl --request GET \
--url http://localhost:8080/v1/gtfs_feeds/mdb-1/datasets
```
- Verify that datasets are sorted adequately from newest to oldest.
Partial JSON example:
```
[
{
"id": "dataset-1",
"feed_id": "mdb-1",
"hosted_url": "https://example.com/mdb-1",
"note": null,
"downloaded_at": "2024-02-01T00:00:00Z",
......
},
{
"id": "dataset-2",
"feed_id": "mdb-1", …
```

fix: add descending order to gtfs datasets endpoint

---

api/src/scripts/populate_db.py
api/tests/integration/populate_tests/conftest.py
api/tests/integration/populate_tests/test_data/sources_test.csv
api/tests/integration/populate_tests/test_populate.py

**Summary:**
Adding tests for https://github.com/MobilityData/mobility-feed-api/pull/1053

fix: Added some tests for the populate script

---

api/src/scripts/populate_db_gtfs.py
functions-python/reverse_geolocation/src/location_group_utils.py
functions-python/reverse_geolocation/tests/test_location_group_utils.py

**Summary:**
Add protecting logic to avoid errors while processing an "invalid" country code.
Invalid country codes must not raise an exception.
The following script must pass locally:
```
./scripts/docker-localdb-rebuild-data.sh --populate-data
```

fix: avoid exception when country code is not found

---

web-app/src/app/screens/Feed/index.tsx

closes #1076 
**Summary:**
When going on a gtfs_rt feed without the `gtfs_rt` in the url (ex: https://mobilitydatabase.org/feeds/mdb-2424) and click on an associated feed, it would break with a react hook error leading to a blank page.
When going on a gtfs_rt feed page, the user should be able to navigate to the associated feeds (gtfs_rt or not in the url) with nothing breaking.
Go on any gtfs_rt link (and manually to some gtfs_rt links without adding `gtfs_rt` in the url) and click on the associated links, it shouldn't give an error
**The fix**
React didn't like `condition ? useSelector() : useSelector()` due to how it's handled in the state queue. Solution, get both selectors then select the correct one with the condition
Please make sure these …

fix: gtfs rt associated feed navigation blank

---

web-app/cypress/e2e/feeds.cy.ts
web-app/public/locales/en/feeds.json
web-app/src/app/screens/Feed/PreviousDatasets.tsx
web-app/src/app/screens/Feed/index.tsx
web-app/src/app/store/dataset-reducer.ts
web-app/src/app/store/dataset-selectors.ts
web-app/src/app/store/saga/dataset-saga.ts
web-app/src/app/utils/dataset.spec.ts
web-app/src/app/utils/dataset.ts

closes #540 
**Summary:**
There can be 100+ datasets, this PR loads them in batches of 10 at a time
When the Feed detail page initially loads, there should be 10 datasets (max) that loads. If the user scrolls to the bottom of the datasets, it will load more and show a loading indicator. Once all of them are loaded, a message saying "all datasets are loaded" will appear and will not make any more calls
Go to any feed detail page and see if the datasets show accordingly.
NOTE: I wasn't able to find any feeds in QA / Dev that had more than 10 datasets. This PR was tested with PROD data. Some PROD feeds with 10+
```
101	"mdb-1896"
101	"mdb-1884"
101	"mdb-761"
101	"mdb-1784"
```
Please make sure these boxes are checked before submitting your pull …

Feat: dataset pagination

---

web-app/src/app/screens/Feed/PreviousDatasets.tsx

closes #1067 
**Summary:**
In the feed detail page, in the dataset history section, when there isn't a validation report, the user wasn't able to download the dataset (even though the dataset url existed). This PR allows users to download datasets even if the validation report isn't present
You should be able to download a dataset even if there are no validation report for it
Go to feed: `mdb-100` and see that you have the ability to download the dataset even if the validation report isn't there. You can test this on any feed

fix: download datasets when no validation report

---

web-app/src/app/components/OfficialChip.tsx
web-app/src/app/screens/Feed/DataQualitySummary.tsx
web-app/src/app/screens/Feed/index.tsx

closes #1070 
**Summary:**
Display Official Tag on gtfs rt page when applicable
When a gtfs rt feed has the official tag property, it should display the tag
Go to any gtfs rt feed on dev and see if the tag is there.
These are the official feeds in dev
```
"mdb-1911"
"mdb-1912"
"mdb-2401"
"mdb-2402"
"mdb-2403"
"mdb-2405"
"mdb-2406"
"mdb-2409"
"mdb-2410"
"mdb-2422"
"mdb-2423"
"mdb-2424"
"mdb-2427"
"mdb-2428"
"mdb-2429"
"mdb-1910"
```

fix: official tag to gtfs_rt detail page

---

workflows/gtfs_validator_execution.yml

**Summary:**
This PR deletes the waitForTaskCompletion step in the  GTFS validator's workflow. This is the strep causing the cost to skyrocket. This RP reduces the ability to know when the GTFS validator process fails for a particular feed. However, this will be addressed as part of #1029  
As a secondary fix, this PR increases the interval time from 10s to 30s for expecting a response from the validator and increases the waiting time to 60 minutes.
Part of #1089 
The workflow spending time is reduced.
Go to DEV environment and run a workflow with the proposed structure from this PR.

fix: GTFS validator GCP workflow takes too much time to complete

---

docs/OperationsAPI.yaml
functions-python/operations_api/src/feeds_operations/impl/models/update_request_gtfs_feed_impl.py
functions-python/operations_api/src/feeds_operations/impl/models/update_request_gtfs_rt_feed_impl.py
functions-python/operations_api/tests/feeds_operations/impl/test_feeds_operations_impl_gtfs.py
functions-python/operations_api/tests/feeds_operations/impl/test_feeds_operations_impl_gtfs_rt.py

**Summary:**
This PR add official field  as a boolean in the operational API update endpoint.
Official status for feed can be added via the operational api updated endpoint

feat: add official field in the operational API update endpoint

---

.github/workflows/db-update.yml

**Summary:**
Part of #675 
This pull request includes changes to the `.github/workflows/db-update.yml` file to streamline the database update process by removing the steps related to downloading and processing the `systems.csv` file for GBFS. The most important changes include the removal of steps for downloading `systems.csv`, getting its full path, updating the database content with GBFS data, and uploading the GBFS log file for verification.
Streamlining the database update process:
* Removed steps for downloading `systems.csv`, getting its full path, and updating the database content with GBFS data.
* Removed the step for uploading the GBFS log file for verification.
GBFS populate script is not executed when the mobility database catalog merge event is …

fix: remove gbfs populate script from mdb catalog trigger

---

web-app/src/app/components/NestedCheckboxList.spec.tsx
web-app/src/app/components/NestedCheckboxList.tsx
web-app/src/app/screens/Feeds/index.tsx

**Summary:**
closes: #842 
Enhancements to the checkbox filter found on the feeds search page
- Disabled state
- Debounce when multi select
- Refactor code to use recursive component
1. When selecting 'GTFS Realtime' and 'GTFS Schedule' is not selected. The Features filter will be disabled. If the user has already selected features, they will be de-selected and all the expanding elements closed. Once the Feature filter is no longer disabled, the state will return back to what it was
2. When selecting features in rapid succession, the app will wait 500ms before triggering a search call
Go to the Feeds Search page and play around with the filters and keep an eye on the chips. UX feedback is also appreciated. 
NOTE: Feature filter does not work with …

Feat: checkbox filter enhancements

---

functions-python/helpers/feed_status.py
functions-python/process_validation_report/src/main.py
functions-python/update_feed_status/src/main.py
functions-python/update_feed_status/tests/conftest.py
functions-python/update_feed_status/tests/test_update_feed_status_main.py

**Summary:**
closes #1114 
When the validation report is run, it will also update the feed status based on the new service date ranges.  The update feed status function was also refactored to accept specific feed ids to optimize the query
When the validation report is processed, it should update the feeds status based on the incoming service date range.
Run the update feed status function and it should work as normal. Run the process validation report function and it should also update the feed status based on the service date range

feat: udpate feed status on validation report

---

functions-python/batch_process_dataset/src/main.py
functions-python/process_validation_report/src/main.py
functions-python/process_validation_report/tests/test_validation_report.py

**Summary:**
Fixes #1126 
Two fixes:
- Commit the dataset as soon as possible after uploading the file to the bucket
- Trigger the retry mechanism in the process validation report function if the dataset is not present in the DB
The retry mechanism is triggered when the dataset is not found in the DB and the dataset is committed as soon is the file is uploaded to the bucket.
This can be tested in a real environment but it's not consistently present as depends on concurrent calls and timing of the events.

fix: process validation report when dataset is not committed to the DB yet

---

api/src/scripts/populate_db_gtfs.py

**Summary:**
The populate script is setting the status to 'active' for all feeds it processes, which can lead to wrong feed statuses. This PR sets the feed status to active only if it's a new feed. 
When the populate script runs, it shouldn't update the feed status for existing feeds

fix: update populate script -> feed status only on new feeds

---

docs/OperationsAPI.yaml
functions-python/operations_api/src/feeds_operations/impl/feeds_operations_impl.py
functions-python/operations_api/tests/feeds_operations/impl/test_feeds_operations_impl_gtfs.py
functions-python/operations_api/tests/feeds_operations/impl/test_feeds_operations_impl_gtfs_rt.py
functions-python/operations_api/tests/feeds_operations/impl/test_get_feeds.py
liquibase/changelog.xml
liquibase/changes/feat_1132.sql
liquibase/changes/feat_1132_2.sql

**Summary:**
This PR adds "unpublished" as an operational_status to the operations_api allowing feeds to be set to unpublished. Feeds set to unpublished can all be searched via the get endpoint.
Feed can set to unpublished

feat: add operational status of "unpublished" to opeartions_api

---

functions-python/helpers/feed_status.py

**Summary:**
In #953 the objective was to log the differences in the feed status updates. We return the difference as a json object but we never log them, and GCP logs do not display the response. The objective of this PR is to log the differences
It should log the differences when running update feed status functions
Run update_feed_status and see if it logs out the difference

fix: log the status diff

---

api/src/scripts/populate_db_test_data.py
api/tests/integration/test_feeds_api.py
api/tests/test_data/extra_test_data.json
integration-tests/src/endpoints/gbfs_feeds.py

**Summary:**
- Added integration test cases to validate filtering by provider, version, and system_id on the GBFS endpoint.
- Expanded integration tests in the feeds API to cover various filter parameters and expected outcomes.
- Updated the database test population script to support GBFS versions and endpoints.

test: improved test coverage for gbfs endpoints

---

api/src/scripts/populate_db_gtfs.py

**Summary:**
The change ensures that the `status` field is set to "deprecated" if the corresponding value in the CSV file indicates it. 
Related to: #1143
The deprecated status is set to the feed if it's coming from the CSV.
This can be tested locally if the populate script is executed with a non-empty DB.
Tested in DEV with [action](https://github.com/MobilityData/mobility-feed-api/actions/runs/14715398487/job/41297556697)

fix: override deprecated status from csv

---

functions-python/helpers/query_helper.py

**Summary:**
This PR fixes the bug that makes operations feeds endpoint fail when called without data_type filtering. Added a filter to filter out gbfs feeds from the get endpoint
Get feeds endpoint can be call without data_type filtering.

bug: fix bug making operations feeds endpoint fail when called without data_type filtering

---

web-app/src/app/screens/Feeds/index.tsx
web-app/src/app/utils/consts.tsx

**Summary:**
With feature filtering, we do not want the user to filter through deprecated feature names
deprecated features should not appear in the search
Go on the search page and look for deprecated features

fix: remove deprecated features from search filters

---

web-app/src/app/utils/consts.tsx

**Summary:**
closes #1169 
The wrong text-to-speech feature was deprecated, this corrects that so that the feature filter works
When filtering by text-to-speech, it should show results
On feeds search, filter by text to speech and see results

fix: text to speech feature filter

---

functions-python/gbfs_validator/src/gbfs_data_processor.py
functions-python/gbfs_validator/tests/test_gbfs_data_processor.py
liquibase/changelog.xml
liquibase/changes/feat_1124.sql

**Summary:**
Closes #1124 
This PR adds the autodiscovery URL to the list of endpoints when it's not explicitly defined in the GBFS response per version. Also, populate the current data in PROD. 
The autodiscovery URL is always persisted in the DB as a GBFS endpoint.
SQL update executed in DEV and executed the gbfs-batch function in DEV, the following query verified that there are no gbfs versions without the `gbfs` endpoint:
```
SELECT feed.stable_id, gbfsversion.*
FROM gbfsversion
inner join feed on gbfsversion.feed_id = feed.id
WHERE NOT EXISTS (
SELECT 1
FROM gbfsendpoint ge
WHERE ge.gbfs_version_id = gbfsversion.id
AND ge.name = 'gbfs'
);
```
GBFS endpoint added to a feed that don't have GBFS endpoint listed in version 1.1:
Please make sure …

feat: Add gbfs endpoint to the GBFSVersion entity

---

docs/OperationsAPI.yaml

**Summary:**
This PR adds "future" status to feed types in Operations API
"future" is now a feed status ypes in Operations API

Feat: add "future" status to feed types in Operations API

---

api/src/feeds/impl/models/search_feed_item_result_impl.py
api/src/feeds/impl/search_api_impl.py
api/tests/integration/test_search_api.py
docs/DatabaseCatalogAPI.yaml
liquibase/changelog.xml
liquibase/changes/feat_1118.sql
web-app/src/app/services/feeds/types.ts

**Summary:**
- Added `versions` field to the `FeedSearch` materialized view and exposed it in the search API response for GBFS feeds
- Introduced a new optional `versions` query parameter to the `/search` endpoint  
→ Accepts a comma-separated list (e.g. `?versions=2.2,3.0`)  
→ Filters feeds that support **any** of the specified versions (logical OR)
**Notes:**
- Version filtering is only applied when the `versions` parameter is provided and non-empty
- Supports exact matches on version strings as returned by the backend (e.g. `"2.2"`, `"3.0"`)
Run API locally.
```http
GET /v1/search?data_type=gbfs&versions=2.2,3.0
``` 

feat: added versions filtering to search

---

web-app/public/locales/en/gbfs.json
web-app/src/app/screens/Feed/components/GbfsVersions.tsx

**Summary:**
closes #1104 
In gbfs feed detail if there are no versions, it will display an error message
In gbfs feed detail if there are no versions, it will display an error message
Go to `feeds/gbfs/gbfs-maribor` and see that there are no versions

feat: gbfs error message for no versions

---

web-app/src/app/screens/Feeds/index.tsx

**Summary:**
closes #1187 
When going on the feeds search page, the data formats are not auto selected anymore
When you go to the feeds page, the data formats should not be auto selected
Go to the feeds page from the header or from the home page, it should be empty

feat: removed default search selection

---

web-app/src/app/screens/Feed/Feed.functions.tsx
web-app/src/app/screens/Feed/Feed.spec.tsx

**Summary:**
closes #1193 
When going on the feed detail page, the title of the page updates to relevant gbfs text
When going on the feed detail page, the title of the page updates to relevant gbfs text
Title is in format: `Flamingo Porirua GBFS Feed - Mobility Database`
Go on any feed detail page and the title should be relevant to gtfs gtfs_rt or gbfs

fix: gbfs update title on detail page

---

web-app/src/app/screens/Feeds/index.tsx
web-app/src/app/screens/Home.tsx

**Summary:**
Issue describing: https://github.com/MobilityData/mobility-feed-api/issues/1184
closes: #1184 
When clicking on the home search input (empty), it would trigger a flicker in the search page. This PR fixes that
When clicking on the home search input, it should not create a flicker effect in the search page
From the home page, click on the 'search' button, it should go to the search page with no issues
** KNOWN BUG **
The issue underlying is that going to the URL `feeds/q=` will cause that flicker to occur. It's a deeper issue about updating the url to remove the invalid search and the data types at the same time. I will create a different ticket to tackle this as it's quite a complex bug to fix, and now can only be re-produced by going …

fix: home page flickering bug

---

.github/workflows/typescript-generator-check.yml
docs/DatabaseCatalogAPI.yaml
web-app/src/app/services/feeds/types.ts

Closes #1144
Added some duplications of the data_type property used in the feeds, gtfs_feeds, gtfs_rt_feeds and gbfs_feeds.
This resulted in examples being appropriate for the type of feed.
The generated feed code (feed_gen) stayed the same with this change.

fix: Corrected the data_type property examples in the OpenApi schemas

---

functions-python/export_csv/src/main.py

**Summary:**
Part of #1027 
This PR updates the logging calls to the new standardized pattern on the export csv function.

chore: update logging for the CSV export function

---

api/src/shared/database/database.py
functions-python/backfill_dataset_service_date_range/src/main.py
functions-python/backfill_dataset_service_date_range/tests/test_backfill_dataset_service_date_range_main.py
functions-python/helpers/feed_status.py
functions-python/tasks_executor/README.md
functions-python/tasks_executor/src/main.py
functions-python/tasks_executor/src/tasks/validation_reports/README.md
functions-python/tasks_executor/src/tasks/validation_reports/rebuild_missing_validation_reports.py
functions-python/update_feed_status/src/main.py
functions-python/update_feed_status/tests/test_update_feed_status_main.py

**Summary:**
Part of #1027 
This PR updates the logging calls to the new standardized pattern on the update tasks functions.

chore: improve logs on update tasks functions

---

api/src/shared/database/database.py
functions-python/helpers/feed_status.py
functions-python/update_feed_status/src/main.py
functions-python/update_feed_status/tests/test_update_feed_status_main.py

**Summary:**
Part of #1027 
This PR updates the logging calls to the new standardized pattern on the update feed status function.

chore: improve logs on update feed status function

---

api/src/middleware/request_context_middleware.py

**Summary:**
This PR adds the missing tracking information for API usage. The log records contain a label python_logger equal to "api-access-log".
Logs are available in the local and dev environments.

fix: missing tracking information in api logs

---

web-app/public/locales/en/feeds.json
web-app/src/app/screens/Feed/index.tsx

**Summary:**
Giving attribution to transitland and fta when using their data
On feed detail pages that have external sources of `tld` or `ntd` it will display an attribution for transitland and fta repectfully. Clicking the name will bring you to licensed page
Go on a feed with tld or ntd and see the attribution

feat: transitland and fta attribution

---

web-app/src/app/utils/date.spec.ts
web-app/src/app/utils/date.ts

**Summary:**
Closes #1241 
This PR allows date parameters to be null or undefined.
The blank page issue is fixed for the offending feeds
The following URL should render correctly:
- https://mobility-feeds-dev--pr-1267-yszhktsg.web.app/feeds/gbfs-voi_Antwerp
- https://qa.mobilitydatabase.org/feeds/gbfs-voi_Antwerp (This has prod data and failed with previous releases)

fix: prepare validated_at to be null when validation report is not returned

---

functions-python/helpers/query_helper.py
functions-python/reverse_geolocation/src/reverse_geolocation_batch.py
functions-python/tasks_executor/README.md
functions-python/tasks_executor/requirements.txt
functions-python/tasks_executor/src/main.py
functions-python/tasks_executor/src/tasks/missing_bounding_boxes/rebuild_missing_bounding_boxes.py
functions-python/tasks_executor/tests/tasks/bounding_boxes/test_rebuild_missing_bounding_boxes.py
infra/functions-python/main.tf

**Summary:**
add support for the rebuild_missing_bounding_boxes task, enable the detection and processing of GTFS datasets missing bounding box information.

fix: 1204 bounding boxes are missing for many feeds with good stopstxt files

---

api/src/scripts/gbfs_utils/comparison.py
api/src/scripts/populate_db_gbfs.py
api/src/shared/database/database.py
api/tests/integration/cascade_delete/conftest.py
api/tests/integration/cascade_delete/test_cascade_delete.py
api/tests/integration/populate_twice_gbfs/conftest.py
api/tests/integration/populate_twice_gbfs/test_data/systems_test.csv
api/tests/integration/populate_twice_gbfs/test_data_part_2/systems_test.csv
api/tests/integration/populate_twice_gbfs/test_populate_gbfs.py
api/tests/test_utils/database.py
functions-python/operations_api/src/feeds_operations/impl/feeds_operations_impl.py
liquibase/changelog.xml
liquibase/changes/feat_1265_cascade_delete.sql
scripts/function-python-setup.sh

Closes #1242 
Closes #1268 
The two corrections are:
- Deleted feeds from the DB if removed form systems.csv
- There was code that would filter out feeds that were in in the DB but not in systems.csv. Thus we did not know that some feeds were removed from systems.csv
-  Stopped processing feeds based on changes in location
- The location is initially set with the populate scripts from systems.csv, but then it is changed by the function that determines the location from the data. So comparing locations to see if something changed in CSV did not work.
For deletion, this PR also setup cascade deletes on certain DB tables in the SQL schema. For example, id a GbfsFeed is deleted, the entry in gbfsversion table referring to this feed is also deleted. This prevent failing of the deletion because …

fix: 2 corrections on gbfs populate

---

functions-python/helpers/utils.py

**Summary:**
Datasets were not downloaded for mdb-2684.
mdb-2684 has type 1 authentication, meaning the token is passed as a query in the URL.
The base URL for this feed is: `http://api.511.org/transit/datafeeds?operator_id=CE`
The code would just append `?api_key=...` to the base url, giving a resulting url with two `?`
The correction is to use the `&` separator if the URL already has a `?`.
Note this could fix other feeds with the same configuration.

Fix: problem fetching datasets with type 1 authentication.

---

api/src/shared/common/gcp_utils.py
api/src/shared/database/database.py
functions-python/reverse_geolocation/src/reverse_geolocation_processor.py
functions-python/reverse_geolocation/tests/test_reverse_geolocation_processor.py
functions-python/tasks_executor/tests/tasks/geojson/test_update_geojson_files_precision.py
functions-python/update_feed_status/tests/conftest.py
functions-python/update_feed_status/tests/test_update_feed_status_main.py
liquibase/changelog.xml
liquibase/changes/feat_fix_geolocation_circular_dep.sql

**Summary:**
In #1353 we introduced `feed. geolocation_file_created_date` and `feed. geolocation_file_dataset_id` fields to track the generation og the geolocation files per feed. All current feeds were updated with the information as part of #1353 issue. In this PR, we are updating the geolocation generation to persist those fields for the new added datasets.
The feed. geolocation_file_created_date` and `feed. geolocation_file_dataset_id` fields are populated as part of the location extraction process.
This can tested in local using the reverse_geolocation_process_verifier.py.

feat: update feed geolocation information

---

functions-python/batch_process_dataset/src/main.py
functions-python/batch_process_dataset/src/scripts/download_verifier.py
functions-python/helpers/tests/test_helpers.py
functions-python/helpers/utils.py

**Summary:**
Closes MobilityData/mobility-database-catalogs#917
This PR adds the referer URL to the download feed request headers.
The referer URL is added to the download feed header with the producer url as a value.
Use the download_verifier with `https://www.vre.org/gtfs/google_transit.zip`

feat: add referer header to download request

---

web-app/src/app/components/CoveredAreaMap.tsx

**Summary:**
The GTFS visualization view is now only enabled if the `enableGtfsVisualizationMap` configuration is set to true.

hotfix: visualization feature flag

---

functions-python/helpers/requirements.txt
functions-python/helpers/tests/test_helpers.py
functions-python/helpers/utils.py
functions-python/pmtiles_builder/requirements.txt
functions-python/pmtiles_builder/src/csv_cache.py
functions-python/pmtiles_builder/src/main.py
functions-python/pmtiles_builder/src/scripts/pmtiles_builder_verifier.py

**Summary:**
Fixes #1358 
This PR adds a `detect_encoding` function to be used by the file loaders. This makes sure the file and columns are properly loaded.
In Python, opening a UTF-8 file with encoding="utf-8" doesn’t remove a `BOM` if present, so the first string may contain a hidden \ufeff. Using encoding="utf-8-sig" strips the BOM automatically and avoids this issue.
_A BOM (Byte Order Mark) is a special hidden character at the start of some text files that indicates the file’s encoding. In UTF-8 it isn’t needed, but some editors add it anyway._
CSV files with BOOM characters are properly read.
Use the verifier with feed id mdb-733 and dataset id mdb-733-202509111637.
Please make sure these boxes are checked before submitting your pull …

fix: pmtiles generation fails with error: route_id

---

.github/workflows/build-test.yml
.github/workflows/datasets-batch-deployer.yml
.github/workflows/db-update.yml
.github/workflows/integration-tests-pr.yml

**Summary:**
This PR fixes the failing Liquibase installation on CI Ubuntu GitHub Actions. The failure is due to changes in permissions at the Liquibase repository. This PR modifies the installation process to utilize the tar file. As part of the PR, the Liquibase version was updated to the latest 4th release.
**Out of scope**: upgrade liquibase version to 5+
GitHub actions depending on Liquibase must pass.
Review the action logs 

fix: failing liquibase installation

---

functions-python/pmtiles_builder/src/main.py
functions-python/tasks_executor/src/tasks/visualization_files/rebuild_missing_visualization_files.py
functions-python/tasks_executor/tests/conftest.py
functions-python/tasks_executor/tests/tasks/validation_reports/test_rebuild_missing_validation_reports.py
functions-python/tasks_executor/tests/tasks/visualisation_files/test_rebuild_visualization_files.py

**Summary:**
**From our AI friend:**
This pull request refactors the logic for rebuilding missing visualization files, with a focus on simplifying configuration, improving testability, and adding new filtering capabilities. The most significant changes include removing the dependency on the `DATASETS_BUCKET_NAME` environment variable, eliminating unused GCS bucket/file checks, and introducing support for filtering datasets by feed operational status. Related tests and fixtures have been updated to match the new logic.
**Refactoring and configuration simplification:**
* Removed all code and test logic related to the `DATASETS_BUCKET_NAME` environment variable and GCS storage client interactions (including the `bucket_name` parameter and `PMTILES_FILES` checks) from …

feat: refactor Pmtiles build using visualization_dataset_id to check existence
