.gitignore
docs/DB_SELECTION.md

Evaluate and propose the Database engine for supporting the MobilityData Catalog API.
Closes #1

feat: engines selection doc

---

docs/DatabaseCatalogAPI.yaml

Added GTFS realtime endpoints and modified to conform to the latest DB schema.
Closes https://github.com/MobilityData/mobility-feed-api/issues/11

Adding gtfs rt

---

docs/DatabaseCatalogAPI.yaml

**Summary:**
Related to https://github.com/MobilityData/mobility-feed-api/issues/49 but changes with filter and sort not included in this PR.
Also included changes for https://github.com/MobilityData/mobility-feed-api/issues/23
- Added the v1 version prefix
- Moved {id} and gtfs around in the endpoint urls.
- Updated some descriptions and names
- Added feed logs and redirects
The swagger should show the changes and not have any errors.

feat: 49 minor api changes

---

api/src/feeds/impl/datasets_api_impl.py
api/src/feeds/impl/feeds_api_impl.py
api/src/feeds/impl/metadata_api_impl.py
docs/DatabaseCatalogAPI.yaml

**Summary:**
- Add operationId to OpenAPI schema to align function names with OpenAPI schema
- Add missing get_feed_logs function implementation
- Fixes current 500 response in DEV and QA
Part of #21 
Operation id is added to the schema and it's reflected in the python generated code.

chore: Add operationId to OpenAPI schema

---

api/requirements.txt
api/src/feeds/filters/feed_filter.py
api/src/feeds/filters/gtfs_dataset_filter.py
api/src/feeds/filters/gtfs_feed_filter.py
api/src/feeds/filters/gtfs_rt_feed_filter.py
api/src/feeds/impl/datasets_api_impl.py
api/src/feeds/impl/feeds_api_impl.py
docs/DatabaseCatalogAPI.yaml

**Summary:**
this adds `fastapi-filter` on top of the changes open in #90. Merge this into #90 before merging #90 into main.

integrate fastapi-filter to feeds endpoint

---

.github/workflows/web-app.yml
README.md

**Summary:**
Fix conditional issue added by #115.
Part of #101.
Prod login is not triggered on push to main branches.

fix: web-app gh action release conditional

---

docs/DatabaseCatalogAPI.yaml

**Summary:**
Add QA environment address to Openapi schema

chore: add QA environment address to Openapi schema

---

docs/DatabaseCatalogAPI.yaml

**Summary:**
Fix API OpenAPI QA address

fix: API QA address

---

.github/workflows/api-prod.yml
.github/workflows/db-prod.yml
.github/workflows/db-update-prod.yml
docs/GCP.md

feat: 98 setup prod environment for api

---

.github/workflows/db-update-dev.yml
.github/workflows/db-update-prod.yml
.github/workflows/db-update-qa.yml
.github/workflows/db-update.yml

**Summary:**
On workflow_dispatch GH action is failing due to the parameters are defined as boolean instead of string(only supported type by GH input actions), [failing example](https://github.com/MobilityData/mobility-feed-api/actions/runs/6747980194)
DB update action runs successfully on workflow_dispatch.

fix: Database update action

---

.github/workflows/web-app.yml
docs/DatabaseCatalogAPI.yaml
docs/DatabaseCatalogAPI_IAP.yaml
web-app/.firebaserc
web-app/package.json
web-app/src/app/screens/Account.tsx

**Summary:**
- Add Firebase production environment to firebase configuration and deployment. 
- Add beta release address to OpenApi schema
Closes #98 

feat: add firebase prod environment

---

docs/DatabaseCatalogAPI.yaml
docs/DatabaseCatalogAPI_IAP.yaml

**Summary:**
Changed according to comment in https://github.com/MobilityData/mobility-feed-api/pull/150

feat: Changed a description in the openapi file.

---

.github/PULL_REQUEST_TEMPLATE.md

**Summary:**
As per Retrium action item I am adding a section about testing tips to the PR template.

feat: Added a testing tips section.

---

.github/workflows/web-app.yml
web-app/babel.config.js
web-app/jest-global-setup.ts
web-app/package.json
web-app/src/app/App.test.tsx
web-app/src/app/screens/Account.tsx
web-app/src/app/utils/date.spec.ts
web-app/src/app/utils/date.ts
web-app/tsconfig.json
web-app/yarn.lock

**Summary:**
- Detects when the access token is expired(the expired date is in the past) and stops the timer.
- Setup jest unit test framework and add it to the GH actions
Fixes #138
After the access token is expired, the message "Token expired" is visible instead of the counter.

fix: access token timer counts in incrementing order after token expired

---

web-app/src/app/screens/Account.tsx

**Summary:**
Closes #176 
Changed the curl command to point to the PROD endpoint and disabled the display of the token within the API test block
Login to your account and generate an access token -- the token should not be displayed in the `API Test` box but will be properly copied to your clipboard. 

fix: curl command and preview fixes

---

web-app/src/app/Theme.ts
web-app/src/app/screens/Account.tsx

**Summary:**
Adds token authentication content to the Account page.
Closes #181 
The code snippet for generating the access token should be visible on the Account page.
- Sign in 
- On the account page, verify that access token generation in visible
- Click on copy to clipboard(access token section)
- Open a terminal and paste the command
- Verify that the API URL is pointing to the production environment, https://api.mobilitydatabase.org/v1/tokens
- If you are testing in DEV or QA, replace `api` hostname with `api-dev` or `api-qa`
- Hit enter and expect a JSON response with a valid access token.

feat: Adds token authentication content to the Account page

---

docs/DatabaseCatalogAPI.yaml

**Summary:**
Fixed the example value of the component field with a valid enum value.

fix:  components field example

---

README.md

**Summary:**
Closes #171 
Created documentation in `README.md` for how consumers authenticate to access the API

feat: authentication documentation

---

.github/workflows/datasets-batch-deployer-dev.yml
functions-python/README.md
functions-python/batch_datasets/src/main.py
functions-python/batch_process_dataset/function_config.json
functions-python/batch_process_dataset/src/main.py
functions-python/batch_process_dataset/tests/test_batch_process_dataset_main.py
functions-python/helpers/utils.py
infra/batch/main.tf

**Summary:**
This PR integrates support for authenticated feeds into the historical datasets batch processing workflow.
Closes #172 
Feeds with `authentication_type` set to `1` or `2` will have their credentials transmitted via URL or header, respectively. 
Authenticated Feed Examples in DEV Environment:
- mdb-1846: https://storage.googleapis.com/mobilitydata-datasets-dev/mdb-1846/latest.zip 
- mdb-1847: https://storage.googleapis.com/mobilitydata-datasets-dev/mdb-1847/latest.zip
- Set Up Google Cloud CLI:
- Install and configure the `gcloud` CLI. 
- Set the active project to `mobility-feeds-dev`.
- Prepare Test Payload
- Create a payload with the authenticated feed information. Example payload:
``` json
{"execution_id": …
```

feat: batch process for storing historical datasets from a GTFS authenticated feed

---

.github/workflows/db-update-prod.yml
.github/workflows/db-update-qa.yml

Fixing GH action -- missing parameter `DB_IP`.

fix: db-update qa and prod

---

liquibase/changelog.xml
liquibase/changes/feat_240.sql

feat: validation schema updates

---

docs/DatabaseCatalogAPI.yaml

**Summary:**
Make all labels in OpenAPI definition snake case
No API change. Swagger document should show snake case

fix:217 make all labels snake case

---

.github/workflows/build-test.yml
.gitignore
api/.coveragerc
functions-python/batch_datasets/.coveragerc
functions-python/batch_datasets/tests/test_batch_datasets_main.py
functions-python/batch_process_dataset/.coveragerc
functions-python/batch_process_dataset/requirements_dev.txt
functions-python/batch_process_dataset/tests/test_batch_process_dataset_main.py
functions-python/batch_process_dataset/tests/test_helpers.py
functions-python/dataset_service/.coveragerc
functions-python/dataset_service/requirements_dev.txt
functions-python/dataset_service/tests/test_dataset_service.py
functions-python/helpers/.coveragerc
functions-python/helpers/requirements.txt
functions-python/helpers/requirements_dev.txt
functions-python/helpers/tests/test_helpers.py
functions-python/tokens/.coveragerc
scripts/api-tests.sh

**Summary:**
This PR addresses the task of adding tests for the historical dataset batch processing (closes #105). In addition to implementing the necessary tests, this PR introduces improvements to our testing framework:
- Test Coverage Enhancement: Coverage has been added to the tests to ensure a more robust and reliable codebase.
- Coverage Threshold : A coverage threshold (currently 85% branch coverage) has been set in our workflows. This ensures that all future contributions maintain a high standard of code quality and test coverage.
**Expected Behaviour:**
With the new tests and coverage enhancements, we expect:
- More comprehensive testing of the historical dataset batch processing.
- An automated check for test coverage in PRs
Logs extracted from the Build & Test action
**Testing …

feat: added coverage and tests to historical batch processing

---

api/.coveragerc
api/requirements_dev.txt
api/src/database/database.py
api/tests/test_database.py
docs/DatabaseCatalogAPI.yaml

**Summary:**
Closes #249 
✅ Removed `enum` type from the `components` list
✅ Updated `database.py` related tests to achieve threshold coverage

feat: updated components from enum to string

---

.github/workflows/api-deployer.yml
.github/workflows/datasets-batch-deployer-prod.yml
.github/workflows/web-app.yml
infra/global/vars.tf

**Summary:**
This PR introduces fixes to make sure the batch processing workflow works as expected in PROD.
Closes #233 
✅ database updates for adding feeds with and without authentication
✅ historical dataset processing
✅ bounding box extraction
✅ feed retrieval w and w/o auth

fix: batch processing in PROD

---

web-app/src/app/components/Footer.tsx
web-app/src/app/screens/Home.tsx

**Summary:**
Closes #265 
✅ Added feedback lint to `Footer.tsx`
✅ Updated feed count from 1800+ to 2000+

feat: add feedback link to UI + update feed count

---

web-app/src/app/screens/FAQ.tsx

**Summary:**
Missing space before Canonical GTFS Schedule Validator link

add space before link

---

functions-python/batch_process_dataset/requirements.txt
functions-python/batch_process_dataset/src/main.py
functions-python/batch_process_dataset/tests/test_batch_process_dataset_main.py
infra/batch/main.tf
infra/batch/vars.tf

**Summary:**
Added `files.mobilitydatabase.org` domain name to the batch storage bucket. Added the following names pere environment:
- PROD(not created yet) => files.mobilitydatabase.org
- QA(not created yet) => qa-files.mobilitydatabase.org
- DEV(not created yet) => dev-files.mobilitydatabase.org
Files can be downloaded from files.mobilitydatabase.org example: https://files.mobilitydatabase.org/mdb-10/latest.zip (Not available currently)
- This PR needs to be tested after merging as the reserved IP address will happen when terraform is applied.
- Download files a feed file from  the dev DNS, for example https://dev-files.mobilitydatabase.org/mdb-10/latest.zip
- Execute batch functions to verify that the DNS added to the DB matches with the newly …

feat: Add our own DNS to GCP bucket links 

---

docs/DatabaseCatalogAPI.yaml

**Summary:**
Update all parameter naming to be all snake_case and remove the unused filter parameter [issue-238](https://github.com/MobilityData/mobility-feed-api/issues/238)
Changes are in the naming of parameters in the yaml, so there shouldn't be any UI changes.
As long as the current automated tests pass, I think it should be fine. There is no change to existing logic and no new logic is introduced. 
- [ x ] Run the unit tests with `./scripts/api-tests.sh` to make sure you didn't break anything
- [ x ] Add or update any needed documentation to the repo
- [ x ] Format the title like "feat: [new feature short description]". Title must follow the Conventional …

doc: issue-238: update parameter naming and remove filter param

---

docs/DatabaseCatalogAPI.yaml

**Summary:**
Closes #284 
Using swagger, doing a `Try it out` on any of the API endpoints shouild give some result (ie no error or empty list)

feat: Made API examples work out of the box

---

.github/workflows/build-test.yml
.github/workflows/datasets-batch-deployer.yml
.github/workflows/db-update.yml

We are following [official Liquibase documentation](https://docs.liquibase.com/start/install/liquibase-linux-debian-ubuntu.html) for installing it on Ubuntu machines. Starting from today(2024-02-16) installation and package verification is failing with message
```
W: GPG error: https://repo.liquibase.com/ stable InRelease: The following signatures were invalid: EXPKEYSIG C[60](https://github.com/MobilityData/mobility-feed-api/actions/runs/7932028884/job/21658045603#step:7:61)4A7DC47B41156 Liquibase <support@liquibase.org>
E: The repository 'https://repo.liquibase.com/ stable InRelease' is not signed.
```
Example of failing build [here](https://github.com/MobilityData/mobility-feed-api/actions/runs/7932028884/job/21658045603).
The released package is not properly signed, or the signature …

fix: liquibase installation

---

api/src/feeds/impl/datasets_api_impl.py
api/tests/test_database.py
api/tests/test_datasets_api.py
api/tests/test_utils/database.py

**Summary:**
add validation report for gtfs datasets
- [] Run the unit tests with `./scripts/api-tests.sh` to make sure you didn't break anything

feat: validation report

---

infra/batch/vars.tf
scripts/tunnel-create.sh

- Fixed a typo on the files URL.
- Add a sleep command to the tunnel script to allow the machine to be up and functional before creating the tunnel. Without the sleep command, the tunnel script fails intermittently.
The URL parameter `PUBLIC_HOSTED_DATASETS_URL` is set properly with the `.org` root domain in the cloud run function.
- Deploy this branch to DEV environment
- Review the Cloud run parameter PUBLIC_HOSTED_DATASETS_URL in the DEV environment for the _batch-process-dataset-dev_ function.

fix: files public url

---

docs/DatabaseCatalogAPI.yaml
web-app/src/app/screens/Account.tsx
web-app/src/app/screens/SignIn.tsx

**Summary:**
Changes:
- Reordered account components to align them to the user authentication workflow.
- Added authentication workflow documentation to the OpenAPI specification.
- Replaced _Swagger_ by _OpenAPI_ in the account page text.
Closes #321 
Layout matches #321 screenshot.
- Open the PR deployed link and verify the account layout.
Local deployment screenshot:

feat: minor improvements to account page

---

.github/workflows/api-deployer.yml
.github/workflows/api-dev.yml
.github/workflows/api-prod.yml
.github/workflows/api-qa.yml
infra/main.tf
infra/terraform-init/main.tf
infra/vars.tf
infra/vars.tfvars.rename_me
infra/workflows/main.tf
infra/workflows/vars.tf
workflows/gtfs_validator_execution.yml

**Summary:**
Closes #339 
The changes implemented in this PR are designed to automate the validation process, ensuring that the datasets folders are consistently augmented with the GTFS validation report. This automation is achieved through the introduction of a GCP Workflow that triggers the validator post-dataset download using the GTFS Validator's web services.
From `mobility-feeds-dev` project:
- [HTML report example for dataset `mdb-742-202403212257`](https://storage.googleapis.com/mobilitydata-datasets-dev/mdb-742/mdb-742-202403212257/report.html)
- [JSON report example for dataset `mdb-742-202403212257`](https://storage.googleapis.com/mobilitydata-datasets-dev/mdb-742/mdb-742-202403212257/report.json)
- Execution logs:
- **Using GCP …

feat: execute the GTFS Validator after downloading a dataset

---

api/.openapi-generator/FILES
api/src/feeds/impl/models/search_feeds200_response_results_inner_impl.py
api/src/feeds/impl/search_api_impl.py
api/src/main.py
api/src/scripts/populate_db.py
api/tests/test_search_api.py
api/tests/test_utils/database.py
api/tests/unittest/models/test_search_feeds200_response_results_inner_impl.py
docs/DatabaseCatalogAPI.yaml
functions-python/batch_process_dataset/src/main.py
functions-python/helpers/database.py
functions-python/test_utils/database_utils.py
liquibase/changelog.xml
liquibase/changes/feat_371.sql

**Summary:**
Changes
- Add a materialized view for indexing feeds. Added all returned fields to the view to reduce DB calls.
- Implemented search endpoint querying the view with pattern '{query}:*', allowing incomplete lexemes in the queries.
- Refresh the materialized view after inserting data.
**Performance considerations**
We included all fields in the view to avoid multiple DB calls per HTTP request, which impacts the view's size. However, the current size is still small: ~1.6MB. We should monitor this size as the DB grows in the number of feeds.
DEV test was performed with the following results:
|    |  Time  |  Response Size  |  
|---|---|---|
|  limit=100, search_query=us | <150ms   |  90kb
|  limit=200, search_query=us  | <250ms   |  180kb
|  no limit, search_query=us  | ~1s   | …

feat: search endpoint implementation

---

functions-python/helpers/database.py
functions-python/update_validation_report/.coveragerc
functions-python/update_validation_report/.env.rename_me
functions-python/update_validation_report/README.md
functions-python/update_validation_report/function_config.json
functions-python/update_validation_report/requirements.txt
functions-python/update_validation_report/requirements_dev.txt
functions-python/update_validation_report/src/main.py
functions-python/update_validation_report/tests/test_update_validation_report.py
functions-python/validation_report_processor/src/main.py
infra/functions-python/main.tf
infra/functions-python/vars.tf
infra/workflows/main.tf
scripts/function-python-run.sh
workflows/gtfs_validator_execution.yml

**Summary:**
This PR addresses issue #395 by introducing a new cloud function designed to update validation reports for all `latest` datasets in a batch process.
**Details:**
This enhancement is triggered (e.g., upon a GTFS Validator release) to perform batch validations. It retrieves all datasets tagged as `latest` and checks their corresponding validation reports stored in GCP against the most recent validation version available via the web validator. For any dataset lacking the latest report version, the function updates the associated GCP `Blob` metadata—including retry count and validation version. This metadata aids in managing update attempts, ensuring that datasets that are repeatedly invalid do not continue to retry indefinitely. Following metadata updates, the corresponding GCP …

feat: Implement script to update existing datasets with validator reports

---

docs/DatabaseCatalogAPI.yaml

**Summary:**
Closes #432 
Minor changes to the api after manual QA testing

fix: 432 modify api schema to conform to expected behavior for 11 release

---

docs/DatabaseCatalogAPI.yaml

**Summary:**
Part of #442 
Enhance search endpoint documentation. No implementation changed, only addition of OpenAPI documentation on the search endpoint.

doc: enhance search endpoint documentation

---

.github/workflows/validator-update.yml

- Removed the action from DEV
- Fixed the queue name

fix: task queue

---

web-app/src/app/App.tsx
web-app/src/app/router/ProtectedRoute.tsx
web-app/src/app/screens/Feed/index.tsx
web-app/src/app/screens/Feeds/index.tsx
web-app/src/app/services/profile-service.ts
web-app/src/app/store/dataset-reducer.ts
web-app/src/app/store/feed-reducer.ts
web-app/src/app/store/feeds-reducer.ts
web-app/src/app/store/saga/auth-saga.ts
web-app/src/app/store/saga/dataset-saga.ts
web-app/src/app/store/saga/feed-saga.ts
web-app/src/app/store/saga/feeds-saga.ts

**Summary:**
This PR addresses using the user's access token while requesting the feed's API endpoints. Principles considered for using the Firebase SDK function instead of the redux state for the API token management:
- Previously the access token used is the one saved in the redux store. This token was initially saved in redux as part of the account screen. Using this token can lead to cases where the token is already created before the user hits the account screen, having the code to manage different entry stages to the create access token button. In addition, access tokens expire every hour, so we will need to handle the rotation of the token and the implications of this process on the current account's page. There is a potential race condition when updating a token to the redux …

fix: use firebase access token directly instead of redux saved token

---

.github/workflows/datasets-batch-deployer-prod.yml

**Summary:**
Following investigation [#297 ](https://github.com/MobilityData/mobility-database-catalogs/issues/375), the batch processing schedule in the production environment has been updated. The new schedule ensures that batch processing occurs every Monday and Thursday at midnight, effectively covering periods of 3 and 4 days.

feat: changing schedule to every Monday and Thursday

---

.github/workflows/build-test.yml
README.md
config/.env.local
docker-compose.yaml
scripts/db-gen.sh
scripts/docker-localdb-rebuild-data.sh

**Summary:**
closes #551 
Modified so the tests are not dependant on the existence of the main database.
Tests should run locally and in build-test.yml.

feat: 551 tests should be using the test database

---

web-app/cypress/e2e/feeds.cy.ts
web-app/cypress/fixtures/feed_datasets_test-516.json
web-app/cypress/fixtures/feed_test-516.json
web-app/cypress/fixtures/gtfs_feed_test-516.json
web-app/src/app/components/Map.tsx
web-app/src/app/screens/Feed/DataQualitySummary.tsx
web-app/src/app/screens/Feed/FeedSummary.tsx
web-app/src/app/screens/Feed/PreviousDatasets.tsx
web-app/src/app/screens/Feed/index.tsx

closes #512 #513
does not mock API call
**Summary:**
`yarn cypress:run` 
```
Running:  feeds.cy.ts                                                                     (2 of 6)
Feed page
✓ should render feed title and provider (2092ms)
✓ should render the last updated date (722ms)
✓ should render download button (645ms)
✓ should render data quality summary (741ms)
✓ should render feed summary (702ms)
✓ should render dataset history (680ms)
✓ should render feature chips (692ms)
✓ should have working links to validation reports (714ms)
8 passing (7s)
(Results)
┌────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Tests:        8                                                                                │
│ Passing: …
```

adds basic cypress testing for Feeds page

---

functions-python/extract_bb/README.md
functions-python/extract_bb/src/main.py
functions-python/extract_bb/tests/test_extract_bb.py
infra/functions-python/main.tf

**Summary:**
Closes #590
This PR introduces a batch version of the cloud function responsible for extracting bounding boxes from datasets. This enhancement addresses the need for a more efficient processing method, allowing multiple datasets to be processed concurrently.
**Changes Made:**
- **Conversion to Pub/Sub Triggered Function:** The core logic of the function has been moved to a Pub/Sub triggered function. This change enables the batch process to initiate multiple dataset extractions without having to wait for each one to complete sequentially.
- **Retention of Eventarc Triggered Function:** The existing function triggered by Eventarc, which activates when a new dataset is uploaded to the GCP datasets bucket, remains unchanged.
- **New HTTP Triggered Batch Function:** A new HTTP …

feat: create a cloud function to extract bounding boxes in batch

---

functions-python/dataset_service/main.py
functions-python/extract_bb/.coveragerc
functions-python/extract_bb/function_config.json
functions-python/extract_bb/src/main.py
functions-python/extract_bb/tests/test_extract_bb.py
infra/batch/main.tf
infra/functions-python/main.tf

Part of #618 — This update implements necessary fixes for the bounding box extraction function, enabling future location extraction:
- **Error Handling**: Added missing try/catch blocks to prevent infinite retries.
- **Resource Allocation**: Increased memory and CPU limits because of insufficient memory problems.
- **Trace Logging**: Introduced logging for bounding box extraction, with updates to `DatasetTraceService` and the `extract_bb` module.
Enhancements in error handling, resource management, and visibility for bounding box extraction processes.
- Follow testing procedures from PR #631.
- Ensure processes skip if execution limits exceed (`MAXIMUM_EXECUTIONS` default is `1`).
- Check the functionality and logging accuracy for bounding box extraction.
Testers are encouraged to explore …

fix: infinite retries of `extract_bounding_box_pubsub`

---

.github/workflows/db-update-qa.yml

**Summary:**
As #451 the Database update script was deleted. We still need to update QA DB on main branches pushes to keep the QA DB in sync with the liquibase state.
Database Update(QA) script is executed after main branch pushes.

fix: revert Database Update(QA) deletion

---

.github/workflows/web-app-deployer.yml
.github/workflows/web-dev.yml
.github/workflows/web-prod.yml
.github/workflows/web-qa.yml
functions/firebase.json
functions/packages/feed-form/.eslintrc.js
functions/packages/feed-form/.gitignore
functions/packages/feed-form/jest.config.ts
functions/packages/feed-form/package.json
functions/packages/feed-form/src/__tests__/feed-form.spec.ts
functions/packages/feed-form/src/impl/feed-form-impl.ts
functions/packages/feed-form/src/index.ts
functions/packages/feed-form/tsconfig.dev.json
functions/packages/feed-form/tsconfig.json
functions/yarn.lock
web-app/src/app/screens/FeedSubmission/Form/index.tsx

closes #553 
**Summary:**
Creates a typescript cloud function to submit a new feed data to google sheets. 3 environments were created: DEV, QA, PROD. Due to the messy nature of our existing google sheet, it was advised to start a fresh google sheet.
Note: A follow up ticket will be made to include calling the Slack webhook and well as github
**Environments**
Environments for DEV QA and PROD can be found in the EXTERNAL Shared Drive
https://drive.google.com/drive/folders/1gOu6qf8p6n-wa-4MQH6ouDj6cgxaPwhO
Everyone in MobilityData has access to this folder, but people from the outside will need to be invited
**Cloud Changes**
1. Enabled Google Sheets API for QA and PROD
2. Created Service Emails dedicated for Google Sheet API access for DEV -> saved in 1Password
**Expected behavior:** …

Feat: typescript submit feed form cloud function

---

functions/packages/feed-form/src/impl/feed-form-impl.ts

**Summary:**
Add proper firebase logger to better debug errors for the submit feed form function
To show better formatted logs 

fix: proper logger added to submit feed form

---

web-app/package.json
web-app/src/app/screens/About.tsx
web-app/src/app/screens/Home.tsx
web-app/src/app/styles/FAQ.css
web-app/yarn.lock

closes #691 
**Summary:**
Various ui ux issues that got fixed
1. About button has been fixed, now the entire button is clickable - including the icon
2. On the Home page, the "the Canonical GTFS Schedule Validator" button now opens in a new tab
3. Removed the numbers animation, weird bugs with the library. Will revisit when more time (post gtfs.org)
1. Check the About page and click anywhere on the "learn more about mobilitydata" button
2. Go to home page and click "the Canonical GTFS Schedule Validator" button, it should open in new tab
3. See no more number animation 

Fix: UI / UX general fixes

---

functions-python/helpers/locations.py
functions-python/helpers/requirements.txt
functions-python/helpers/tests/test_locations.py
functions-python/preprocessed_analytics/.coveragerc
functions-python/preprocessed_analytics/README.md
functions-python/preprocessed_analytics/function_config.json
functions-python/preprocessed_analytics/requirements.txt
functions-python/preprocessed_analytics/requirements_dev.txt
functions-python/preprocessed_analytics/src/main.py
functions-python/preprocessed_analytics/src/processors/base_analytics_processor.py
functions-python/preprocessed_analytics/src/processors/gbfs_analytics_processor.py
functions-python/preprocessed_analytics/src/processors/gtfs_analytics_processor.py
functions-python/preprocessed_analytics/tests/test_base_processor.py
functions-python/preprocessed_analytics/tests/test_gbfs_processor.py
functions-python/preprocessed_analytics/tests/test_gtfs_processor.py
functions-python/preprocessed_analytics/tests/test_main.py
infra/metrics/main.tf
infra/metrics/vars.tf

**Summary:**
This PR introduces the implementation of two Google Cloud Functions, `process_analytics_gtfs` and `process_analytics_gbfs`, which automate the monthly retrieval, processing, and storage of analytics data for GTFS and GBFS datasets. These functions are scheduled to run once a month via GCP Scheduler and store the resulting analytics in the specified Google Cloud Storage buckets.
The changes include the creation of base and specific analytics processors, responsible for handling the data retrieval, processing metrics, and saving the results in JSON format. 
**Expected behavior:**
- Upon execution, the `process_analytics_gtfs` function retrieves the latest GTFS dataset per feed, processes it to extract metrics related to validation notices, features, and geographical locations, …

feat: automate gtfs & gbfs data preprocessing for analytics

---

web-app/cypress/e2e/changepassword.cy.ts

**Summary:**
Temporarily skip `changepassword.cy.ts` due to it's flaky nature of failing the pipeline 
changepassword.cy.ts should not run in the pipeline
Will make a follow up ticket to address fixing it

fix: temp disable change password cypress test

---

web-app/src/app/components/Header.tsx
web-app/src/app/screens/FAQ.tsx
web-app/src/app/screens/Home.tsx
web-app/src/app/styles/TextShimmer.css

closes #720 
**Summary:**
Various UI / UX changes mainly on the landing page
- The header links can now "open in new tab"
- The header logo + text is now aligned
- The landing page has new headline text + animation
- landing page mobile styling has been fixed
- text changes on landing page and faq
All styles should look good on all browsers and all responsive formats
Go on the landing page with any browser, assure all the styles at any responsive size looks good

Feat: UI corrections

---

.github/workflows/web-pr.yml
functions/packages/feed-form/src/__tests__/feed-form.spec.ts
functions/packages/feed-form/src/impl/feed-form-impl.ts
functions/packages/feed-form/src/impl/types.ts
functions/packages/feed-form/src/index.ts
web-app/package.json
web-app/public/locales/en/common.json
web-app/public/locales/en/feeds.json
web-app/src/app/screens/FeedSubmission/Form/FirstStep.tsx
web-app/src/app/screens/FeedSubmission/Form/FourthStep.tsx
web-app/src/app/screens/FeedSubmission/Form/SecondStep.tsx
web-app/src/app/screens/FeedSubmission/Form/SecondStepRealtime.tsx
web-app/src/app/screens/FeedSubmission/Form/ThirdStep.tsx
web-app/src/app/screens/FeedSubmission/Form/index.tsx
web-app/src/app/services/feeds/add-feed-form-service.ts
web-app/src/app/services/feeds/utils.spec.ts
web-app/src/app/services/feeds/utils.ts
web-app/yarn.lock

closes #657 and #738
**Summary:**
Dynamic form behaviour for add new feed. 
- Conditional functionality
- third page added
- error handling
- country dropdown list
- translation keys
Ability to submit the form to google sheet
The form should display different fields for gtfs and gtfs_rt
The third page should be the same for both
If "update feed" for rt, show 3 more fields
All required fields will show errors if not provided
For RT an error will show if no feeds are entered
Ability to submit the form
Go through the add-feed form and see if anything is un clear or glitchy functionality. Once you submit the form, you should be able to see the data in the DEV google sheet
https://docs.google.com/spreadsheets/d/1iXwux9hM4p5Li1EGgwx-8hU3sMDnF15yTflqmGjiZ …

feat: add feed form, conditional functionality + submit

---

web-app/cypress/e2e/addFeedForm.cy.ts
web-app/cypress/support/commands.ts
web-app/cypress/support/index.ts
web-app/src/app/screens/FeedSubmission/Form/FirstStep.tsx
web-app/src/app/screens/FeedSubmission/Form/FourthStep.tsx
web-app/src/app/screens/FeedSubmission/Form/SecondStep.tsx
web-app/src/app/screens/FeedSubmission/Form/SecondStepRealtime.tsx
web-app/src/app/screens/FeedSubmission/Form/ThirdStep.tsx
web-app/src/app/screens/FeedSubmitted.tsx
web-app/src/app/store/saga/auth-saga.ts
web-app/src/app/store/store.ts
web-app/src/index.tsx
web-app/tsconfig.json

closes #658 
**Summary:**
Added e2e tests for the add feed form flow and fixed login bug
All the e2e tests should pass
Run the e2e tests
Terminal 1: `yarn run start:dev`
Terminal 2: `yarn run cypress:open`
GUI will open where you will be able to run the e2e tests
** Learnings **
E2e tests are slow, we should be conscious of what kind of tests we write. It should cover the main paths of a feature and not all the edge cases.

feat: add feed form e2e

---

functions-python/update_validation_report/README.md
functions-python/update_validation_report/src/main.py
functions-python/update_validation_report/tests/test_update_validation_report.py
workflows/gtfs_validator_execution.yml

**Summary:**
This update introduces new parameters to the `update-validation-report` function and the `gtfs-validator-execution` workflow to support the generation of snapshot validation reports in PROD. This enhancement allows us to perform analytics on the GTFS validator's pre-release versions.
- **`validator_endpoint` parameter**: 
- If a `validator_endpoint` parameter is provided to the HTTP batch function, it will be passed to the workflow, overriding the default endpoint specified in the environment variable.
- When the provided URL differs from the one defined in the environment variable, validation reports generated using this snapshot validator will not be added to the database to prevent serving them via the API. However, these reports will still be ingested into BigQuery for …

feat: support snapshot validation reports in PROD

---

web-app/src/app/App.css
web-app/src/app/components/ContentBox.tsx
web-app/src/app/components/Header.tsx
web-app/src/app/screens/About.tsx
web-app/src/app/screens/Account.tsx
web-app/src/app/screens/Contribute.tsx
web-app/src/app/screens/FAQ.tsx
web-app/src/app/screens/Feed/AssociatedFeeds.tsx
web-app/src/app/screens/Feed/PreviousDatasets.tsx
web-app/src/app/screens/Feed/index.tsx
web-app/src/app/screens/Feeds/index.tsx
web-app/src/app/styles/Account.css

closes: #740 
**Summary:**
- [Side Menu] on mobile hid the metrics when not logged in with proper account + added gbfs metrics
- [Account] is now mobile friendly + refined spacing
- [Feeds / Feed / About / FAQ / Login / Create Account]: margin / spacing adjustments
NOTE: the metrics page wasn't touched to be mobile friendly
When running the application on a mobile screen, it should look proper
Do a general sweep of the application on a mobile screen size 
9b-bfca-3055ff45d6a9)

Feat: mobile enhancements

---

docker-compose.yaml
infra/postgresql/main.tf

**Summary:**
Updated QA database to version 13 
[Log of operations](https://console.cloud.google.com/sql/instances/mobilitydata-database-instance/operations?inv=1&invt=AbidYg&project=mobility-feeds-qa)

feat: upgrade psql version

---

web-app/src/app/interface/RemoteConfig.ts
web-app/src/app/screens/Feed/DataQualitySummary.tsx
web-app/src/app/screens/Feed/Feed.spec.tsx

**Summary:**
Feature flag to hide feed status. Values updated in firebase already
Should not show feed status chip if behind feature flag
FF: ON
FF: OFF

feat: feature flag for feed status

---

infra/functions-python/main.tf

**Summary:**
Fix terraform config

fix: terraform hotfix for backfill-dataset-service-date-range

---

functions-python/extract_location/src/reverse_geolocation/geocoded_location.py

Nomatium blocked our requests because of the user agent. According to their documentation, the user agent needs to represent the application. 

hotfix: location extraction nomatium user agent

---

infra/batch/main.tf

**Summary:**
This pull request includes a change to the `infra/batch/main.tf` file to configure CORS settings for the datasets Google Storage Bucket.

fix: datasets bucket cors config

---

infra/functions-python/main.tf
web-app/src/app/components/CoveredAreaMap.tsx

**Summary:**
- Fixed missing permission for the SA to create cloud tasks in QA
- Fixed UI behaviour when the dataset or location extraction geojson is unavailable

fix: location extraction permission and ui behaviour bugs

---

functions-python/preprocessed_analytics/src/processors/gtfs_analytics_processor.py

**Summary:**
Closes https://github.com/MobilityData/product-tasks/issues/129

fix: only keep published feeds in gtfs metrics dashboard

---

docs/DatabaseCatalogAPI.yaml
web-app/src/app/services/feeds/types.ts

**Summary:**
`future` status for feeds have recently been introduced to the database but the API schema has not been changed accordingly causing a validation failure resulting in the integration tests to fail.

fix: missing feature status

---

api/src/feeds/impl/feeds_api_impl.py
api/src/shared/common/db_utils.py
functions-python/export_csv/src/main.py
functions-python/export_csv/tests/conftest.py

**Summary:**
This PR includes changes to the GTFS feed handling and database query functions to improve efficiency and consistency. 

fix: uniformize db query for gtfs feeds entities

---

api/src/feeds/impl/feeds_api_impl.py
api/src/shared/common/db_utils.py
liquibase/changelog.xml
liquibase/changes/add_idxs.sql

**Summary:**
Summarize the changes in the pull request including how it relates to any issues (include the #number, or link them).

fix: is_official filter and add SQL indexes

---

infra/batch/main.tf

**Summary:**
Part of #1045 
switching to Autoclass
ensure always using the most cost-effective storage class without sacrificing performance or availability in datasets storage bucket

feat: 1045 datasets bucket autoclass

---

api/src/feeds/impl/models/search_feed_item_result_impl.py

fix: error when no location is included

---

api/src/shared/common/db_utils.py
functions-python/export_csv/README.md
functions-python/export_csv/requirements.txt
functions-python/export_csv/src/main.py
functions-python/export_csv/tests/conftest.py
functions-python/export_csv/tests/test_export_csv_main.py
liquibase/changelog.xml
liquibase/changes/feat_951.sql

**Summary:**  
The code has been updated to ensure that the produced CSV uses the most appropriate location based on the following criteria:  
- For feeds with extracted locations using the **new process**, the location with the **most stops** is selected. In case of a tie (multiple locations with the same number of stops), the **first location alphabetically** is chosen.  
- For feeds with extracted locations using the **old process**, the **first location alphabetically** is selected. This typically corresponds to the **first country alphabetically**, as multiple locations are only present when there are multiple countries.  
- If the feed contains only **one location**, that location is used as expected.  
Due to these changes, I updated the sorting method to a **natural sort** (e.g., …

feat: use the location with the most stops when exporting the csv

---

web-app/src/app/screens/FAQ.tsx

Closes #1100 
It's all in the title.

Changed the links for the feed spreadsheet and schema in the FAQ

---

web-app/src/app/screens/Feeds/index.tsx

**Summary:**
closes #1137 
added future status to search
Should be able to see feeds with status future in the search page

feat: added future status to search

---

web-app/public/locales/en/common.json
web-app/public/locales/en/feeds.json
web-app/src/app/Theme.ts
web-app/src/app/components/FeedStatus.tsx
web-app/src/app/components/OfficialChip.tsx
web-app/src/app/components/ThemeToggle.tsx
web-app/src/app/screens/Feed/FeedSummary.tsx
web-app/src/app/screens/Feeds/AdvancedSearchTable.tsx
web-app/src/app/screens/Feeds/GtfsRtEntities.tsx
web-app/src/app/screens/Feeds/PopoverList.tsx
web-app/src/app/screens/Feeds/ProviderTitle.tsx
web-app/src/app/screens/Feeds/SearchTable.tsx
web-app/src/app/screens/Feeds/index.tsx
web-app/src/app/screens/Feeds/utility.ts
web-app/src/app/services/feeds/utils.ts
web-app/src/app/utils/consts.tsx

**Summary:**
closes #994 
- Introduces Advanced Search view: displays gtfs features
- Has the option for compact view: current implementation
- Adjusts search page colors / designs to be WCAG contrast compliant
- SEO compliant
Should display the correct data for each data type
gtfs: features
gtfs rt: entity types
gbfs: set but disabled for now
Go on the search page (light mode / dark mode / tablet / mobile / desktop) play around and assure all looks good
normal
dark
available compact view
tablet
mobile
Many locations

feat: New search page design

---

api/src/shared/database/database.py
functions-python/reverse_geolocation/src/reverse_geolocation_processor.py

**Summary:**
Hotfix for duplicate stops key and cascade issue in location extraction.

fix: duplicate key and cascade bug in location extraction

---

.github/workflows/duplicate-prod-db.yml
scripts/duplicate-prod-db/copy-prod-db-to-qa.sh
scripts/duplicate-prod-db/create-dump-bucket.sh
scripts/duplicate-prod-db/post-import.sh

**Summary:**
Closes #1159
I did not create a new workflow, I just added the `release: prereleased` trigger to the Github action to do the PROD->QA DB copy (duplicate-prod-db.yml).
**From now on MobilityDatabase will be overwritten on QA when a prerelease is done.**
Also corrected a problem where the GH action would not stop if there was an error in one of the underlying scripts.
Tested by creating a test release and made sure the action was launched.
Also tested by creating a fake error in one of the scripts and verified that the GH action stopped.

feat: create a workflow for pre release

---

.github/workflows/db-update-dev.yml
.github/workflows/db-update-prod.yml
.github/workflows/db-update-qa.yml
.github/workflows/db-update.yml

**Summary:**
Part of #675 
The GBFS data update should be performed if the workflow is triggered manually or if it's repository dispatch of type `gbfs-systems-updated`.

feat: trigger db update on `systems.csv` change 

---

.github/workflows/db-update.yml

**Summary:**
Fixed typo in action name related to #645

fix: dispatch action typo

---

functions-python/gbfs_validator/src/gbfs_data_processor.py
liquibase/changelog.xml
liquibase/changes/feat_1125.sql

**Summary:**
Closes #1125 
Update gbfsendpoint table to set is_feature = false for specific endpoints

feat: 1125 modifying features in gbfs endpoints

---

web-app/public/locales/en/common.json
web-app/public/locales/en/feeds.json
web-app/src/app/components/ContentBox.tsx
web-app/src/app/components/CoveredAreaMap.tsx
web-app/src/app/components/MapGeoJSON.tsx
web-app/src/app/screens/Feed/Feed.functions.tsx
web-app/src/app/screens/Feed/components/GbfsVersions.spec.tsx
web-app/src/app/screens/Feed/components/GbfsVersions.tsx
web-app/src/app/screens/Feed/index.tsx
web-app/src/app/store/feed-selectors.ts

**Summary:**
closes #1023 
Includes the visualizations for GBFS feeds in the detail page
Includes the proper auto-discovery link in the GBFS feeds detail page
When going to the GBFS feed detail page, you should be able to see the map where the gbfs feed covers. If not, you should see an error message
Links on the gbfs feed detail page
"open feed url (v)
"open feed url"
"view real time visualization"
auto discovery link on versions
"run validation report
should all work and bring you to the correct location
Go on any gbfs feed detail page and assure that you can see the map or the error message
Ex: (link that works): `/feeds/gbfs/gbfs-lime_zurich`
(link that doesn't work): `gbfs/gbfs-nextbike_cx`
**Notes / Issues found**
There a decent amount of …

feat: gbfs visualizations + auto discovery

---

api/src/feeds/impl/feeds_api_impl.py
api/src/feeds/impl/search_api_impl.py
liquibase/changelog.xml
liquibase/changes/feat_1082.sql

feat: changed sort feeds page by created_at 

---

api/src/shared/common/logging_utils.py
functions-python/batch_datasets/src/main.py
functions-python/batch_process_dataset/main_local_debug.py
functions-python/batch_process_dataset/src/main.py
functions-python/batch_process_dataset/tests/test_batch_process_dataset_main.py
functions-python/big_query_ingestion/function_config.json
functions-python/helpers/logger.py

**Summary:**
Part of #1027
In this PR, the batch datasets functions were updated to use a single log mechanism. The logger util was simplified to have a standard log pattern.
This pull request introduces several improvements and refactors across multiple files to enhance logging practices, streamline code, and improve maintainability. The key changes include replacing direct `logging` calls with custom logger instances, introducing structured logging with stable IDs, and updating test cases to reflect these changes.
* Updated `functions-python/batch_datasets/src/main.py` to replace `logging.info` and `logging.error` with `logging.debug` where appropriate and added structured logging for better granularity and debugging. (`[[1]](diffhunk://#diff-a8a68621701466a810751ca076d8728b953b6a7c7e992 …

chore: improve logs in batch functions

---

functions-python/batch_process_dataset/src/main.py
functions-python/helpers/tests/test_helpers.py
functions-python/helpers/utils.py

**Summary:**
This PR adds the response HTTP status code to logs to keep track of downloaded files.
Part of : #1027 
The response HTTP status code is added to the logs

chore: add response http status code to the logs

---

functions-python/gbfs_validator/src/gbfs_data_processor.py
functions-python/gbfs_validator/src/gbfs_utils.py
functions-python/gbfs_validator/src/main.py
functions-python/gbfs_validator/tests/test_gbfs_data_processor.py
functions-python/gbfs_validator/tests/test_gbfs_validator.py

**Summary:**
Part of #1027 
This PR updates the logging calls to the new standardized pattern on the GBFS processing functions.

chore: improve logs on GBFS processing functions

---

functions-python/reverse_geolocation/src/main.py
functions-python/reverse_geolocation/src/parse_request.py
functions-python/reverse_geolocation/src/reverse_geolocation.py
functions-python/reverse_geolocation/src/reverse_geolocation_batch.py
functions-python/reverse_geolocation/src/reverse_geolocation_processor.py
functions-python/reverse_geolocation/tests/test_reverse_geolocation.py
functions-python/reverse_geolocation/tests/test_reverse_geolocation_processor.py
functions-python/reverse_geolocation_populate/src/main.py
functions-python/reverse_geolocation_populate/tests/test_reverse_geolocation_populate.py

**Summary:**
Part of #1027 
This PR updates the logging calls to the new standardized pattern on the reverse geolocation functions.

chore: improve logs on reverse geolocation functions

---

functions-python/process_validation_report/src/main.py
functions-python/process_validation_report/tests/test_validation_report.py
functions-python/update_validation_report/src/main.py
functions-python/update_validation_report/tests/test_update_validation_report.py
functions-python/validation_to_ndjson/src/main.py
functions-python/validation_to_ndjson/src/validation_report_converter.py
functions-python/validation_to_ndjson/tests/test_main.py

**Summary:**
Part of #1027 
This PR updates the logging calls to the new standardized pattern on the validation report processing functions.

chore: improve logs on validation report processing functions

---

functions-python/big_query_ingestion/src/common/bq_data_transfer.py
functions-python/big_query_ingestion/src/main.py
functions-python/big_query_ingestion/tests/test_main.py

**Summary:**
Part of #1027 
This PR updates the logging calls to the new standardized pattern on the BigQuery ingestion functions
**This should be tested as part of #1042 
- Verify that the logs are properly formatted with trace and span ids

chore: update big query ingestion logs

---

api/src/feeds/impl/models/gtfs_dataset_impl.py
api/src/feeds/impl/models/latest_dataset_impl.py
docs/DatabaseCatalogAPI.yaml
functions-python/batch_process_dataset/src/main.py
functions-python/batch_process_dataset/tests/test_batch_process_dataset_main.py
liquibase/changelog.xml
liquibase/changes/feat_1259.sql
web-app/src/app/services/feeds/types.ts

**Summary:**
Closes #1286 
Closes #1259 
Closes #754 
This PR introduces functionality to track and manage the sizes of zipped and unzipped datasets, along with extracted files, across the system. Key changes include updates to database schema, API definitions, backend processing logic, and type definitions in the frontend.
- Enhanced the dataset processing pipeline to handle extracted files and compute zipped/unzipped sizes. This includes:
- Extracting files from zipped datasets and logging them during download.
- Uploading both zipped and extracted files to cloud storage. 
- Storing extracted file metadata and size information in the database.
- Added `extracted_files` and `zipped_size` attributes to the `DatasetFile` class.
- Updated the database schema
- …

feat: unzip and store latest dataset

---

api/requirements.txt
functions-python/backfill_dataset_service_date_range/requirements.txt
functions-python/batch_datasets/requirements.txt
functions-python/batch_process_dataset/requirements.txt
functions-python/big_query_ingestion/requirements.txt
functions-python/export_csv/requirements.txt
functions-python/feed_sync_dispatcher_transitland/requirements.txt
functions-python/feed_sync_process_transitland/requirements.txt
functions-python/gbfs_validator/requirements.txt
functions-python/helpers/requirements.txt
functions-python/operations_api/requirements.txt
functions-python/preprocessed_analytics/requirements.txt
functions-python/process_validation_report/requirements.txt
functions-python/reverse_geolocation/requirements.txt
functions-python/reverse_geolocation_populate/requirements.txt
functions-python/tasks_executor/requirements.txt
functions-python/tokens/requirements.txt
functions-python/update_feed_status/requirements.txt
functions-python/update_validation_report/requirements.txt
functions-python/validation_to_ndjson/requirements.txt
functions/package.json
functions/yarn.lock
web-app/package.json
web-app/yarn.lock

**Summary:**
Denpendabot fixes:
- #746
- #745
- #744
- #743
- #574
- #497

chore(deps): multiple package upgrades by dependabot

---

api/src/shared/common/db_utils.py

**Summary:**
Fixes #1360 
This PR reduces the batch size for fetching the feeds while exporting to the CSV file. It also introduces a batch_size function parameter in case there is a need to fine-tune this value after deployment.
[out of scope]: Review the query to improve memory management and/or increase the SQL temp_file_limit configuration. 
Tested in DEV before the fix, and I got an out-of-memory exception. I tested it after and it worked as expected. 

fix: csv export out of memory

---

functions-python/pmtiles_builder/function_config.json
functions-python/pmtiles_builder/src/main.py
functions-python/pmtiles_builder/src/shapes_index.py
functions-python/pmtiles_builder/tests/test_build_pmtiles.py
infra/batch/main.tf
infra/functions-python/main.tf

See #1384 for the Vancouver visualization.
Shapes.txt lines were not sorted according to the sequence number.
Added the sort and some tests for it.
Also officialized the memory size for the cloud run to 16GB
Here is the corrected vancouver:

fix: Corrected pmtiles code so shape lines are sorted.
